In [7]:
!pip install word2number

Collecting word2number
  Downloading word2number-1.1.zip (9.7 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: word2number
  Building wheel for word2number (pyproject.toml): started
  Building wheel for word2number (pyproject.toml): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5689 sha256=8cb3999124c2402f256c33a033384d61055fe01a8391f0865a102aea6c418c0f
  Stored in directory: c:\users\lakpa\appdata\local\pip\cache\wheels\53\b6\a3\32e61ad7462806c9f50279960156751ff653bb10034f01a86f
Successfully built word2number
Installing collected packages: word2number
Successfully installed word2number-1.1

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from word2number import w2n

In [3]:
data = pd.read_csv(r"hiring.csv")
data

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [4]:
data.experience = data.experience.fillna('zero')
data

  experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [9]:
data.experience = data.experience.apply(w2n.word_to_num)
data

   experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [10]:
data = data.rename(columns={'test_score(out of 10)':'test_score', 'interview_score(out of 10)':'interview_score'})
data

   experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         NaN                7      72000
7          11         7.0                8      80000

In [16]:
# fill test_score , null value with avg score
data.test_score.median()

np.float64(8.0)

In [17]:
data.test_score.mean()

np.float64(7.857142857142857)

In [18]:
import math

In [15]:
avg_score = math.floor(data.test_score.mean())
avg_score

7

In [19]:
data.test_score = data.test_score.fillna(avg_score)
data

   experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         7.0                7      72000
7          11         7.0                8      80000

In [20]:
X = data.drop('salary($)', axis='columns')
X

   experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6
5           3         7.0               10
6          10         7.0                7
7          11         7.0                8

In [22]:
y = data['salary($)']
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary($), dtype: int64

In [23]:
lr = LinearRegression()
lr.fit(X,y)

LinearRegression()

2 yr experience, 9 test score, 6 interview score

12 yr experience, 10 test score, 10 interview score

Answer
53713.86 and 93747.79

In [24]:
lr.predict([[2,9,6]])

D:\my project\codeit_datascience\data_science\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([53713.86677124])

In [25]:
lr.predict([[12,10,10]])

D:\my project\codeit_datascience\data_science\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([93747.79628651])

In [27]:
data

   experience  test_score  interview_score  salary($)
0           0         8.0                9      50000
1           0         8.0                6      45000
2           5         6.0                7      60000
3           2        10.0               10      65000
4           7         9.0                6      70000
5           3         7.0               10      62000
6          10         7.0                7      72000
7          11         7.0                8      80000