# Classification

# it is a supervised ML where the model predict discrete values
# Classification are two types:
1. Binomial classification  : predicts only two values
2: Polynomial classification : predicts more than two values

# Binomial Classification

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [111]:
# load data
data = pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\car cleaned data.csv")
data.head()

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,price,Price
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16,NaN,1.75
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.20,NaN,12.50
2,Chennai,46000,Honda Jazz V,Petrol,Manual,18.20,1199.0,88.70,8.61 Lakh,4.50
3,Chennai,87000,Maruti Ertiga VDI,Diesel,Manual,20.77,1248.0,88.76,NaN,6.00
4,Coimbatore,40670,Audi A4 New 2.0 TDI Multitronic,Diesel,Automatic,15.20,1968.0,140.80,NaN,17.74

In [112]:
# chekc null value
data.isna().sum()

Location           0
run                0
Name               0
fule               0
Transmission       0
Mileage            2
Engine            46
Power            175
price           6247
Price           1234
dtype: int64

In [113]:
data.Engine.agg(['min','max','mean'])

min       72.00000
max     5998.00000
mean    1616.57347
Name: Engine, dtype: float64

In [114]:
data.Power.agg(['min','max','mean'])

min      34.200000
max     616.000000
mean    112.765214
Name: Power, dtype: float64

In [115]:
# replace null value of 'Engine' and 'Power' with its mean value
data['Engine'] = data.Engine.fillna(data.Engine.mean())

In [116]:
data['Power']=data.Power.fillna(data.Power.mean())

In [117]:
# predict fuel type either petrol or diesel, for input variable - mileage, engine and power
data = data[['fule','Mileage','Engine','Power']]
data

        fule  Mileage  Engine   Power
0        CNG    26.60   998.0   58.16
1     Diesel    19.67  1582.0  126.20
2     Petrol    18.20  1199.0   88.70
3     Diesel    20.77  1248.0   88.76
4     Diesel    15.20  1968.0  140.80
...      ...      ...     ...     ...
7248  Diesel    20.54  1598.0  103.60
7249  Petrol    17.21  1197.0  103.60
7250  Diesel    23.08  1461.0   63.10
7251  Petrol    17.20  1197.0  103.60
7252  Diesel    10.00  2148.0  170.00

[7253 rows x 4 columns]

In [118]:
data.fule.unique()

<StringArray>
['CNG', 'Diesel', 'Petrol', 'LPG', 'Electric']
Length: 5, dtype: str

In [119]:
data.fule.value_counts()

fule
Diesel      3852
Petrol      3325
CNG           62
LPG           12
Electric       2
Name: count, dtype: int64

In [120]:
# we select 'diesel', 'petrol' to predict since, both has large records, whereas other fule are less
# we drop other fuel type

In [121]:
# select only 'diesel' or 'petrol'
data = data[data['fule'].isin(['Diesel','Petrol'])]

In [122]:
data.head()

     fule  Mileage  Engine   Power
1  Diesel    19.67  1582.0  126.20
2  Petrol    18.20  1199.0   88.70
3  Diesel    20.77  1248.0   88.76
4  Diesel    15.20  1968.0  140.80
6  Diesel    23.08  1461.0   63.10

In [123]:
data.fule.value_counts()

fule
Diesel    3852
Petrol    3325
Name: count, dtype: int64

In [124]:
# Get sample data for training, such that the dataset contains 1000 rows from each fuel type
df = data.groupby('fule').sample(n=1000)
df

        fule  Mileage  Engine   Power
969   Diesel    21.66  1498.0  103.52
4178  Diesel    22.32  1582.0  126.32
2515  Diesel    17.54  2993.0  313.00
1009  Diesel    25.20  1248.0   74.00
4170  Diesel    21.20  1248.0   75.00
...      ...      ...     ...     ...
6194  Petrol    18.90   998.0   67.10
341   Petrol    11.30  1794.0  125.00
138   Petrol    19.00  1199.0   88.70
6263  Petrol    19.10  1197.0   81.86
4078  Petrol    15.50  1198.0   86.70

[2000 rows x 4 columns]

In [125]:
df.fule.value_counts()

fule
Diesel    1000
Petrol    1000
Name: count, dtype: int64

# create train and test data

In [126]:
X = data.drop('fule', axis=1)
X.head(2)

   Mileage  Engine  Power
1    19.67  1582.0  126.2
2    18.20  1199.0   88.7

In [127]:
y = data.fule
y.head()

1    Diesel
2    Petrol
3    Diesel
4    Diesel
6    Diesel
Name: fule, dtype: str

In [128]:
# split train and test data from X and y
from sklearn.model_selection import train_test_split

In [129]:
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

# train the model with Classifier

In [130]:
# Logistic Regression  --- its a classification model prediction 
from sklearn.linear_model import LogisticRegression

In [131]:
lr = LogisticRegression()

In [132]:
lr.fit(X_train,y_train)

LogisticRegression()

In [133]:
# predict the values
y_pred = lr.predict(X_test)
y_pred

array(['Diesel', 'Diesel', 'Diesel', ..., 'Diesel', 'Petrol', 'Diesel'],
      shape=(1436,), dtype=object)

In [134]:
# check accuracy score
from sklearn.metrics import accuracy_score

In [135]:
acs = accuracy_score(y_test,y_pred)
acs

0.8864902506963789

# Train with other Classifiers and check the accuracy

In [136]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB

In [137]:
# dictionaly for model
mdls = {
    'dt':DecisionTreeClassifier(),
    'rf':RandomForestClassifier(),
    'knn':KNeighborsClassifier(),
    'gn':GaussianNB(),
}

In [138]:
for name, model in mdls.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accs = accuracy_score(y_test,y_pred)
    print("----------")
    print(f"Name: {name}")
    print(f"Accuracy score: {accs}")
    print("-----------")

----------
Name: dt
Accuracy score: 0.9930362116991643
-----------
----------
Name: rf
Accuracy score: 0.995125348189415
-----------
----------
Name: knn
Accuracy score: 0.9874651810584958
-----------
----------
Name: gn
Accuracy score: 0.7103064066852368
-----------

In [73]:
# lets check with sample dataset 'df'
df

        fule  Mileage  Engine   Power
3654  Diesel    23.20  1248.0   73.94
4205  Diesel    25.60  1498.0   98.60
1708  Diesel    15.17  1968.0  181.00
5995  Diesel    19.87  1461.0   83.80
2218  Diesel    13.00  2982.0  168.50
...      ...      ...     ...     ...
5279  Petrol    17.57  1193.0   88.70
6291  Petrol    13.50  1799.0  130.00
868   Petrol    18.90  1197.0   82.00
3445  Petrol    17.30  1061.0   64.00
6335  Petrol    15.10  1196.0   73.00

[2000 rows x 4 columns]

In [75]:
import joblib

In [76]:
for name, model in mdls.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(df.drop('fule', axis=1))
    accs = accuracy_score(df['fule'],y_pred)
    print("----------")
    print(f"Name: {name}")
    print(f"Accuracy score: {accs}")
    print("-----------")
    # save the model
    joblib.dump(model,f"{name}_classifier.pkl")

----------
Name: dt
Accuracy score: 0.9985
-----------
----------
Name: rf
Accuracy score: 0.999
-----------
----------
Name: knn
Accuracy score: 0.9935
-----------
----------
Name: gn
Accuracy score: 0.723
-----------

In [77]:
# here best model accuracy is dt, rf,knn

In [78]:
# we use RandomForestClassifer model --'rf'
# YOlO -- image processing

# Polynomial Classification

In [45]:
# predict more than one discrete value
# load data
data = pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\car cleaned data.csv")
data.head()

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,price,Price
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16,NaN,1.75
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.20,NaN,12.50
2,Chennai,46000,Honda Jazz V,Petrol,Manual,18.20,1199.0,88.70,8.61 Lakh,4.50
3,Chennai,87000,Maruti Ertiga VDI,Diesel,Manual,20.77,1248.0,88.76,NaN,6.00
4,Coimbatore,40670,Audi A4 New 2.0 TDI Multitronic,Diesel,Automatic,15.20,1968.0,140.80,NaN,17.74

In [46]:
# chekc null
data.isna().sum()

Location           0
run                0
Name               0
fule               0
Transmission       0
Mileage            2
Engine            46
Power            175
price           6247
Price           1234
dtype: int64

In [47]:
data.Mileage.dropna(inplace=True)

In [48]:
data['Engine'] = data.Engine.fillna(data.Engine.mean())

In [49]:
data['Power'] = data.Power.fillna(data.Power.mean())

In [50]:
data['Price'] = data.Price.fillna(data.Price.mean())

In [51]:
data.drop('price', axis=1, inplace=True)

In [52]:
data.isna().sum()

Location        0
run             0
Name            0
fule            0
Transmission    0
Mileage         2
Engine          0
Power           0
Price           0
dtype: int64

In [53]:
data.head()

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,Price
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16,1.75
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.20,12.50
2,Chennai,46000,Honda Jazz V,Petrol,Manual,18.20,1199.0,88.70,4.50
3,Chennai,87000,Maruti Ertiga VDI,Diesel,Manual,20.77,1248.0,88.76,6.00
4,Coimbatore,40670,Audi A4 New 2.0 TDI Multitronic,Diesel,Automatic,15.20,1968.0,140.80,17.74

In [54]:
data['Mileage'].sort_values()

7226     0.00
5647     0.00
707      0.00
6697     0.00
6093     0.00
        ...
2059    33.54
2371    33.54
1332    33.54
4446      NaN
4904      NaN
Name: Mileage, Length: 7253, dtype: float64

In [55]:
data[data['Mileage'].isna()]

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,Price
4446,Chennai,50000,Mahindra E Verito D4,Electric,Automatic,NaN,72.0,41.0,13.00
4904,Mumbai,44000,Toyota Prius 2009-2016 Z4,Electric,Automatic,NaN,1798.0,73.0,12.75

In [56]:
data.isna().sum()

Location        0
run             0
Name            0
fule            0
Transmission    0
Mileage         2
Engine          0
Power           0
Price           0
dtype: int64

In [57]:
data.dropna(inplace=True)

In [58]:
data.isna().sum()

Location        0
run             0
Name            0
fule            0
Transmission    0
Mileage         0
Engine          0
Power           0
Price           0
dtype: int64

In [59]:
# export data dataset to csv files
data.to_csv('car_data_cleaned.csv', index=False)

In [61]:
data.head(2)

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,Price
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16,1.75
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.20,12.50

In [63]:
# Predict location on the basis of Mileage, Engine, Power
data = data[['Location','Mileage','Engine','Power']]
data

        Location  Mileage  Engine   Power
0         Mumbai    26.60   998.0   58.16
1           Pune    19.67  1582.0  126.20
2        Chennai    18.20  1199.0   88.70
3        Chennai    20.77  1248.0   88.76
4     Coimbatore    15.20  1968.0  140.80
...          ...      ...     ...     ...
7248   Hyderabad    20.54  1598.0  103.60
7249      Mumbai    17.21  1197.0  103.60
7250     Kolkata    23.08  1461.0   63.10
7251        Pune    17.20  1197.0  103.60
7252       Kochi    10.00  2148.0  170.00

[7251 rows x 4 columns]

In [64]:
data.Location.value_counts()

Location
Mumbai        948
Hyderabad     876
Coimbatore    772
Kochi         772
Pune          765
Delhi         660
Kolkata       654
Chennai       590
Jaipur        499
Bangalore     440
Ahmedabad     275
Name: count, dtype: int64

In [66]:
# Get 200 data from each Location
data = data.groupby('Location').sample(n=200)
data

       Location  Mileage  Engine       Power
7174  Ahmedabad    19.70   796.0   46.300000
6243  Ahmedabad    15.17  1968.0  181.000000
1161  Ahmedabad    20.30  1199.0   84.000000
5755  Ahmedabad    17.00  1086.0  112.765214
500   Ahmedabad    18.90   998.0   67.100000
...         ...      ...     ...         ...
4665       Pune    15.04  1598.0  103.600000
5783       Pune    17.50  1298.0   85.800000
5019       Pune    24.30  1248.0   88.500000
3070       Pune    14.53  1798.0  138.100000
4911       Pune    16.80  1497.0  116.300000

[2200 rows x 4 columns]

In [67]:
data.Location.value_counts()

Location
Ahmedabad     200
Bangalore     200
Chennai       200
Coimbatore    200
Delhi         200
Hyderabad     200
Jaipur        200
Kochi         200
Kolkata       200
Mumbai        200
Pune          200
Name: count, dtype: int64

In [68]:
# Get X and y
X = data.drop('Location',axis=1)
X

      Mileage  Engine       Power
7174    19.70   796.0   46.300000
6243    15.17  1968.0  181.000000
1161    20.30  1199.0   84.000000
5755    17.00  1086.0  112.765214
500     18.90   998.0   67.100000
...       ...     ...         ...
4665    15.04  1598.0  103.600000
5783    17.50  1298.0   85.800000
5019    24.30  1248.0   88.500000
3070    14.53  1798.0  138.100000
4911    16.80  1497.0  116.300000

[2200 rows x 3 columns]

In [70]:
y = data.Location
y

7174    Ahmedabad
6243    Ahmedabad
1161    Ahmedabad
5755    Ahmedabad
500     Ahmedabad
          ...
4665         Pune
5783         Pune
5019         Pune
3070         Pune
4911         Pune
Name: Location, Length: 2200, dtype: str

In [75]:
# Get train and test
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [78]:
for name, model in mdls.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accs= accuracy_score(y_test,y_pred)
    print("-------------")
    print(f"Model: {model}")
    print(f"Accuracy score: {accs}")
    print("------------")

-------------
Model: DecisionTreeClassifier()
Accuracy score: 0.15
------------
-------------
Model: RandomForestClassifier()
Accuracy score: 0.15454545454545454
------------
-------------
Model: KNeighborsClassifier()
Accuracy score: 0.14545454545454545
------------
-------------
Model: GaussianNB()
Accuracy score: 0.11363636363636363
------------

In [79]:
# Accuracy score is not good, although we have taken balance data n=200,
# conclusion : we can say that no relation between 'Location' -- mileage, power, engine.
# cannot predit the location based on 'mileage','power','engine'

# Perform Brand Prediction

In [82]:
data = pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\car_data_cleaned.csv")
data.head()

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,Price
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16,1.75
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.20,12.50
2,Chennai,46000,Honda Jazz V,Petrol,Manual,18.20,1199.0,88.70,4.50
3,Chennai,87000,Maruti Ertiga VDI,Diesel,Manual,20.77,1248.0,88.76,6.00
4,Coimbatore,40670,Audi A4 New 2.0 TDI Multitronic,Diesel,Automatic,15.20,1968.0,140.80,17.74

In [85]:
data['brand']= data.Name.str.split(' ', expand=True)[0]
data.head(2)

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,Price,brand
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16,1.75,Maruti
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.20,12.50,Hyundai

In [89]:
data = data[['brand','Mileage','Engine','Power']]
data.head(2)

     brand  Mileage  Engine   Power
0   Maruti    26.60   998.0   58.16
1  Hyundai    19.67  1582.0  126.20

In [90]:
data.brand.value_counts()

brand
Maruti           1444
Hyundai          1340
Honda             743
Toyota            506
Mercedes-Benz     380
Volkswagen        374
Ford              351
Mahindra          330
BMW               312
Audi              285
Tata              228
Skoda             202
Renault           170
Chevrolet         151
Nissan            117
Land               67
Jaguar             48
Fiat               38
Mitsubishi         36
Mini               31
Volvo              28
Porsche            19
Jeep               19
Datsun             17
ISUZU               3
Force               3
Isuzu               2
Bentley             2
Smart               1
Ambassador          1
Lamborghini         1
Hindustan           1
OpelCorsa           1
Name: count, dtype: int64

In [99]:
# select only 7 
brands = list(data.brand.value_counts().head(7).index)
brands

['Maruti', 'Hyundai', 'Honda', 'Toyota', 'Mercedes-Benz', 'Volkswagen', 'Ford']

In [100]:
data.shape

(7251, 4)

In [103]:
# select the data based on brands only
data = data[data.brand.isin(brands)]
data

              brand  Mileage  Engine   Power
0            Maruti    26.60   998.0   58.16
1           Hyundai    19.67  1582.0  126.20
2             Honda    18.20  1199.0   88.70
3            Maruti    20.77  1248.0   88.76
5           Hyundai    21.10   814.0   55.20
...             ...      ...     ...     ...
7245        Hyundai    21.10   814.0   55.20
7246     Volkswagen    20.54  1598.0  103.60
7247     Volkswagen    17.21  1197.0  103.60
7249     Volkswagen    17.20  1197.0  103.60
7250  Mercedes-Benz    10.00  2148.0  170.00

[5138 rows x 4 columns]

In [104]:
X = data.drop('brand', axis=1)
X

      Mileage  Engine   Power
0       26.60   998.0   58.16
1       19.67  1582.0  126.20
2       18.20  1199.0   88.70
3       20.77  1248.0   88.76
5       21.10   814.0   55.20
...       ...     ...     ...
7245    21.10   814.0   55.20
7246    20.54  1598.0  103.60
7247    17.21  1197.0  103.60
7249    17.20  1197.0  103.60
7250    10.00  2148.0  170.00

[5138 rows x 3 columns]

In [105]:
y = data.brand
y

0              Maruti
1             Hyundai
2               Honda
3              Maruti
5             Hyundai
            ...
7245          Hyundai
7246       Volkswagen
7247       Volkswagen
7249       Volkswagen
7250    Mercedes-Benz
Name: brand, Length: 5138, dtype: str

In [108]:
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [109]:
for name, model in mdls.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    accs= accuracy_score(y_test,y_pred)
    print("-------------")
    print(f"Model: {model}")
    print(f"Accuracy score: {accs}")
    print("------------")

-------------
Model: DecisionTreeClassifier()
Accuracy score: 0.9931906614785992
------------
-------------
Model: RandomForestClassifier()
Accuracy score: 0.9922178988326849
------------
-------------
Model: KNeighborsClassifier()
Accuracy score: 0.9815175097276264
------------
-------------
Model: GaussianNB()
Accuracy score: 0.3521400778210117
------------

In [110]:
# able to predict 'Brand' value on the basis of 'Mileage','Engine','Power' -- so relation exits
# accuracy score is 99% -- decisiontreeClassifer, RandomForesteClassifier, KneighborClassifier