In [1]:
import pandas as pd

In [98]:
data = pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\used_cars_data_uncleaned.csv")
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6/km,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67/km,1582 CC,126.2 bhp,5.0,NaN,12.50

In [99]:
# data cleanig -- fillna(), dropna()
# tranformation -
# droping columns, renmae columns
# Adding or drop columns
# change datatypes
# filling values

# explore data

In [100]:
# info -- data structure
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7253 non-null   str
 9   Engine             7253 non-null   str
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 793.4 KB

In [101]:
# check null values
data.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 0
Engine                  0
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [102]:
# tasks to do--
# drop column --S.no
# drop columns -- New_price, price --- more null values
# change data types --- Mileage, Engine, power to numeric type

In [103]:
# drop column S.No.
data.drop('S.No.', axis=1, inplace=True)

In [104]:
data.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [105]:
data.drop(columns=['New_Price','Price'], inplace=True)

In [106]:
data.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats'],
      dtype='str')

In [107]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6/km,998 CC,58.16 bhp,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67/km,1582 CC,126.2 bhp,5.0

In [108]:
# Before chanign dtypes of column 'Mileage','Engine','Power' -- clean its value
# clean 'Mileage' column values, using split()
data['Mileage'].str.split('/', expand=True)

          0   1
0      26.6  km
1     19.67  km
2      18.2  km
3     20.77  km
4      15.2  km
...     ...  ..
7248  20.54  km
7249  17.21  km
7250  23.08  km
7251   17.2  km
7252     10  km

[7253 rows x 2 columns]

In [109]:
# take the first numeric value and store in same location
data['Mileage']=data['Mileage'].str.split('/',expand=True)[0]

In [110]:
data.Mileage.head()

0     26.6
1    19.67
2     18.2
3    20.77
4     15.2
Name: Mileage, dtype: str

In [111]:
# clean the 'Engine' and 'Power' column using replace()
data['Engine']=data.Engine.str.replace('CC',' ')

In [112]:
data['Power']=data.Power.str.replace('bhp',' ')

In [113]:
data[['Mileage','Engine','Power']].head()

  Mileage  Engine    Power
0    26.6   998    58.16
1   19.67  1582    126.2
2    18.2  1199     88.7
3   20.77  1248    88.76
4    15.2  1968    140.8

In [114]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   str
 1   Location           7253 non-null   str
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   str
 5   Transmission       7253 non-null   str
 6   Owner_Type         7253 non-null   str
 7   Mileage            7253 non-null   str
 8   Engine             7253 non-null   str
 9   Power              7207 non-null   str
 10  Seats              7200 non-null   float64
dtypes: float64(1), int64(2), str(8)
memory usage: 623.4 KB

In [115]:
# change the datatypes of 'Mileage', Engine, Power
data.Mileage = pd.to_numeric(data['Mileage'], errors='coerce')

In [116]:
data.Engine=pd.to_numeric(data.Engine, errors='coerce')

In [117]:
data.Power = pd.to_numeric(data.Power, errors='coerce')

In [118]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   str
 1   Location           7253 non-null   str
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   str
 5   Transmission       7253 non-null   str
 6   Owner_Type         7253 non-null   str
 7   Mileage            7251 non-null   float64
 8   Engine             7207 non-null   float64
 9   Power              7078 non-null   float64
 10  Seats              7200 non-null   float64
dtypes: float64(4), int64(2), str(5)
memory usage: 623.4 KB

In [119]:
data.isna().sum()

Name                   0
Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                2
Engine                46
Power                175
Seats                 53
dtype: int64

In [120]:
# working on fillna values -- mileage, engine, power, seats
# fill seats null value with 5 
data.Seats=data['Seats'].fillna(5)

In [121]:
data.Seats.isna().sum()

np.int64(0)

In [122]:
# fill mileage null value with mean
data.Mileage=data['Mileage'].fillna(data.Mileage.mean())

In [123]:
data.Mileage.isna().sum()

np.int64(0)

In [124]:
data['Mileage'].agg(['min','max','mean'])

min      0.00000
max     33.54000
mean    18.14158
Name: Mileage, dtype: float64

In [125]:
# fill the min value 0.0 with the nearest small value
data[data.Mileage==0.0]['Mileage'].value_counts()

Mileage
0.0    81
Name: count, dtype: int64

In [126]:
# 81 values are 0.0
data[data.Mileage!=0.0]['Mileage'].sort_values()

5781     6.40
5603     7.50
152      7.81
4627     7.94
7057     7.94
        ...
1332    33.54
3129    33.54
2059    33.54
2371    33.54
4141    33.54
Name: Mileage, Length: 7172, dtype: float64

In [127]:
# now fill the mileage 0.0 value by 6.40
data.Mileage = data.Mileage.replace(0.0,6.40)

In [128]:
data.Mileage.min()

np.float64(6.4)

In [129]:
# fill the engine null value with the mean value
data[data.Engine.isna()]['Engine']

194    NaN
208    NaN
733    NaN
749    NaN
1294   NaN
1327   NaN
1385   NaN
1460   NaN
2074   NaN
2096   NaN
2264   NaN
2325   NaN
2335   NaN
2530   NaN
2542   NaN
2623   NaN
2668   NaN
2737   NaN
2780   NaN
2842   NaN
3272   NaN
3404   NaN
3520   NaN
3522   NaN
3810   NaN
4011   NaN
4152   NaN
4229   NaN
4577   NaN
4604   NaN
4697   NaN
4712   NaN
4952   NaN
5015   NaN
5185   NaN
5270   NaN
6042   NaN
6541   NaN
6544   NaN
6633   NaN
6643   NaN
6651   NaN
6677   NaN
6685   NaN
6880   NaN
6902   NaN
Name: Engine, dtype: float64

In [130]:
data[data['Engine']!='NaN']['Engine'].sort_values()

4446     72.0
6120    624.0
4341    624.0
6774    624.0
6826    624.0
        ...
6651      NaN
6677      NaN
6685      NaN
6880      NaN
6902      NaN
Name: Engine, Length: 7253, dtype: float64

In [131]:
data.Engine.agg(['min','max','mean','median'])

min         72.00000
max       5998.00000
mean      1616.57347
median    1493.00000
Name: Engine, dtype: float64

In [132]:
data['Engine']=data.Engine.fillna(data.Engine.mean())

In [133]:
data.Engine.isna().sum()

np.int64(0)

In [134]:
data.Power.agg(['min','max','mean'])

min      34.200000
max     616.000000
mean    112.765214
Name: Power, dtype: float64

In [135]:
data.Power.isna().sum()

np.int64(175)

In [136]:
data[data.Power!='NaN']

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0
...,...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598.0,103.60,5.0
7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0
7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08,1461.0,63.10,5.0
7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.60,5.0
7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170.00,5.0

In [137]:
data[data.Power!='NaN']['Power'].sort_values()

1008    34.2
6226    34.2
2196    34.2
1912    34.2
2849    34.2
        ...
6896     NaN
6902     NaN
6947     NaN
7092     NaN
7145     NaN
Name: Power, Length: 7253, dtype: float64

In [138]:
data.Power.isna().sum()

np.int64(175)

In [139]:
#replace the null value with mean value
data.Power=data.Power.fillna(data.Power.mean())

In [140]:
data[['Mileage','Engine','Power']].isna().sum()

Mileage    0
Engine     0
Power      0
dtype: int64

In [141]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   str
 1   Location           7253 non-null   str
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   str
 5   Transmission       7253 non-null   str
 6   Owner_Type         7253 non-null   str
 7   Mileage            7253 non-null   float64
 8   Engine             7253 non-null   float64
 9   Power              7253 non-null   float64
 10  Seats              7253 non-null   float64
dtypes: float64(4), int64(2), str(5)
memory usage: 623.4 KB

# change column name

In [142]:
data.rename(columns={'Kilometers_Driven':'distance','Fuel_Type':'fule'}, inplace=True)

In [143]:
data.columns

Index(['Name', 'Location', 'Year', 'distance', 'fule', 'Transmission',
       'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats'],
      dtype='str')

# create new column

In [144]:
data.Name.head(2)

0              Maruti Wagon R LXI CNG
1    Hyundai Creta 1.6 CRDi SX Option
Name: Name, dtype: str

In [145]:
# from name column create 'brand' and 'model' columns
data['Name'].str.split(' ', expand=True)

,0,1,2,3,4,5,6,7,8,9
0,Maruti,Wagon,R,LXI,CNG,NaN,NaN,NaN,NaN,NaN
1,Hyundai,Creta,1.6,CRDi,SX,Option,NaN,NaN,NaN,NaN
2,Honda,Jazz,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Maruti,Ertiga,VDI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Audi,A4,New,2.0,TDI,Multitronic,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen,Vento,Diesel,Trendline,NaN,NaN,NaN,NaN,NaN,NaN
7249,Volkswagen,Polo,GT,TSI,NaN,NaN,NaN,NaN,NaN,NaN
7250,Nissan,Micra,Diesel,XV,NaN,NaN,NaN,NaN,NaN,NaN
7251,Volkswagen,Polo,GT,TSI,NaN,NaN,NaN,NaN,NaN,NaN
7252,Mercedes-Benz,E-Class,2009-2013,E,220,CDI,Avantgarde,NaN,NaN,NaN

In [146]:
# create a brand columns
data['Brand']=data['Name'].str.split(' ', expand=True)[0]

In [147]:
# create a model columns
data['Model']=data.Name.str.split(' ',expand=True)[1]

In [148]:
data.head(2)

,Name,Location,Year,distance,fule,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta

In [149]:
# now drop column Name
data.drop('Name', axis=1, inplace=True)

In [150]:
data.head(2)

,Location,Year,distance,fule,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta

In [151]:
# create a new column 'engine type' based on the classification of engine data
data.Engine.agg(['min','max','mean'])

min       72.00000
max     5998.00000
mean    1616.57347
Name: Engine, dtype: float64

In [152]:
# >=500 'Les power', >=1500 ,'Powerfull', >=300, 'High power'
#create a fucntions
def classify(value):
    if value >=3000:
        return 'High Powerfull'
    elif value >=1500:
        return 'Powerfull'
    else:
        return 'Low Powerfull'

In [153]:
data['Engine_Type']=data.Engine.apply(classify)

In [154]:
data.head(2)

,Location,Year,distance,fule,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model,Engine_Type
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon,Low Powerfull
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta,Powerfull

In [156]:
# create a 10% of Power data
data['Power_10%']=data.Power * 0.1

In [157]:
data.head(2)

,Location,Year,distance,fule,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model,Engine_Type,Power_10%
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon,Low Powerfull,5.816
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta,Powerfull,12.620

In [158]:
data.describe()

,Year,distance,Mileage,Engine,Power,Seats,Power_10%
count,7253.000000,7.253000e+03,7253.000000,7253.000000,7253.000000,7253.000000,7253.000000
mean,2013.365366,5.869906e+04,18.213054,1616.573470,112.765214,5.277678,11.276521
std,3.254421,8.442772e+04,4.320489,593.394164,52.844178,0.809039,5.284418
min,1996.000000,1.710000e+02,6.400000,72.000000,34.200000,0.000000,3.420000
25%,2011.000000,3.400000e+04,15.170000,1198.000000,77.000000,5.000000,7.700000
50%,2014.000000,5.341600e+04,18.160000,1493.000000,98.600000,5.000000,9.860000
75%,2016.000000,7.300000e+04,21.100000,1968.000000,138.030000,5.000000,13.803000
max,2019.000000,6.500000e+06,33.540000,5998.000000,616.000000,10.000000,61.600000

In [162]:
df=data.groupby(['Location','Brand','Transmission'])['Mileage'].agg(['min','max','mean','median','std','var'])

In [163]:
df.head()

                                    min    max       mean  median       std  \
Location  Brand     Transmission
Ahmedabad Audi      Automatic      9.74  20.38  14.991538   16.55  3.335238
          BMW       Automatic     11.50  22.69  19.118333   18.68  3.170885
          Chevrolet Automatic     18.10  18.10  18.100000   18.10       NaN
                    Manual        17.80  18.20  18.000000   18.00  0.282843
          Ford      Manual        20.00  23.50  21.583333   21.50  1.744037

                                        var
Location  Brand     Transmission
Ahmedabad Audi      Automatic     11.123814
          BMW       Automatic     10.054509
          Chevrolet Automatic           NaN
                    Manual         0.080000
          Ford      Manual         3.041667

In [164]:
# export both dataset
data.to_csv('datacleaned.csv',index=False)
df.to_csv('Mileage_performance_stat.csv',index=False)