# Data Cleaning and transformation
Handling missing data (fillna, dropna)
Renaming columns,
Adding and dropping columns
data type conversion
Replacing values

In [1]:
import numpy as np
import pandas as pd

In [208]:
# loading dataset
data = pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\used_cars_data_uncleaned.csv")
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6/km,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67/km,1582 CC,126.2 bhp,5.0,NaN,12.50

In [209]:
# DAta cleaning is the process of cleaning or removing unwanted data e.g fillna, dropna
# Changing the data accroding to the requirements is transformation e.g add /rem cols, change data tyeps

In [210]:
# preview the data
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6/km,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67/km,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2/km,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77/km,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2/km,1968 CC,140.8 bhp,5.0,NaN,17.74

In [211]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7253 non-null   str
 9   Engine             7253 non-null   str
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(2), int64(3), str(9)
memory usage: 793.4 KB

In [212]:
# Mileage, Engine, Power must be in float type
data.Power

0       58.16 bhp
1       126.2 bhp
2        88.7 bhp
3       88.76 bhp
4       140.8 bhp
          ...
7248    103.6 bhp
7249    103.6 bhp
7250     63.1 bhp
7251    103.6 bhp
7252      170 bhp
Name: Power, Length: 7253, dtype: str

In [213]:
data.Mileage

0        26.6/km
1       19.67/km
2        18.2/km
3       20.77/km
4        15.2/km
          ...
7248    20.54/km
7249    17.21/km
7250    23.08/km
7251     17.2/km
7252       10/km
Name: Mileage, Length: 7253, dtype: str

In [214]:
data.New_Price

0             NaN
1             NaN
2       8.61 Lakh
3             NaN
4             NaN
          ...
7248          NaN
7249          NaN
7250          NaN
7251          NaN
7252          NaN
Name: New_Price, Length: 7253, dtype: str

In [215]:
data.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 0
Engine                  0
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

# handling null or missing values

In [216]:
# drop or fill
# dropna() --- drop null values
# drop column new_price and price since they have huge amount of null values
data.drop(['New_Price','Price'], axis=1, inplace=True)

In [217]:
data.isna().sum()

S.No.                 0
Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine                0
Power                46
Seats                53
dtype: int64

In [218]:
data.drop('S.No.', axis=1, inplace=True)

In [219]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6/km,998 CC,58.16 bhp,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67/km,1582 CC,126.2 bhp,5.0

In [220]:
# spliting Power columns
data.Power.str.split(' ', expand=True)

          0    1
0     58.16  bhp
1     126.2  bhp
2      88.7  bhp
3     88.76  bhp
4     140.8  bhp
...     ...  ...
7248  103.6  bhp
7249  103.6  bhp
7250   63.1  bhp
7251  103.6  bhp
7252    170  bhp

[7253 rows x 2 columns]

In [221]:
# get the first value and assing in same column
data['Power'] = data.Power.str.split(' ', expand=True)[0]

In [222]:
data.Power.head()

0    58.16
1    126.2
2     88.7
3    88.76
4    140.8
Name: Power, dtype: str

In [223]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6/km,998 CC,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67/km,1582 CC,126.2,5.0

In [224]:
# using replacing values
data['Engine'] = data.Engine.str.replace('CC',' ')

In [225]:
data.Engine.head()

0     998
1    1582
2    1199
3    1248
4    1968
Name: Engine, dtype: str

In [226]:
# using split values for Mileage
data.Mileage.str.split("/", expand=True)

          0   1
0      26.6  km
1     19.67  km
2      18.2  km
3     20.77  km
4      15.2  km
...     ...  ..
7248  20.54  km
7249  17.21  km
7250  23.08  km
7251   17.2  km
7252     10  km

[7253 rows x 2 columns]

In [227]:
data['Mileage'] = data.Mileage.str.split('/',expand=True)[0]

In [228]:
data.Mileage.head(2)

0     26.6
1    19.67
Name: Mileage, dtype: str

In [229]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6,998,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.2,5.0

In [230]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               7253 non-null   str
 1   Location           7253 non-null   str
 2   Year               7253 non-null   int64
 3   Kilometers_Driven  7253 non-null   int64
 4   Fuel_Type          7253 non-null   str
 5   Transmission       7253 non-null   str
 6   Owner_Type         7253 non-null   str
 7   Mileage            7253 non-null   str
 8   Engine             7253 non-null   str
 9   Power              7207 non-null   str
 10  Seats              7200 non-null   float64
dtypes: float64(1), int64(2), str(8)
memory usage: 623.4 KB

In [231]:
# since datatype of Mileage, Engine, and power still string --- change datatype
pd.to_numeric(data['Power'])

ValueError: Unable to parse string "null" at position 76

In [299]:
data['Power'] = pd.to_numeric(data['Power'],errors='coerce')

In [300]:
data['Engine'] = pd.to_numeric(data['Engine'], errors='coerce')

In [301]:
data['Mileage'] = pd.to_numeric(data['Mileage'],errors='coerce')

In [302]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Location      7253 non-null   str
 1   Year          7253 non-null   int64
 2   run           7253 non-null   int64
 3   Fuel_Type     7253 non-null   str
 4   Transmission  7253 non-null   str
 5   owner         7253 non-null   str
 6   Mileage       7253 non-null   float64
 7   Engine        7207 non-null   float64
 8   Power         7078 non-null   float64
 9   Seats         7253 non-null   float64
 10  Brand         7253 non-null   str
 11  Model         7253 non-null   str
 12  Engine_class  7253 non-null   str
 13  Power 10%     7078 non-null   float64
dtypes: float64(5), int64(2), str(7)
memory usage: 793.4 KB

In [303]:
# find and remove the null and missing vlues from mileage, engine, power
data[['Mileage','Engine','Power']].isna().sum()

Mileage      0
Engine      46
Power      175
dtype: int64

In [304]:
# drop mileage null value
data['Mileage'].dropna(inplace=True)

In [305]:
data['Mileage'].isna().sum()

np.int64(0)

In [306]:
# fill null values in Power with mean
data['Power'].fillna(data['Power'].mean())

0        58.16
1       126.20
2        88.70
3        88.76
4       140.80
         ...
7248    103.60
7249    103.60
7250     63.10
7251    103.60
7252    170.00
Name: Power, Length: 7253, dtype: float64

In [307]:
data['Power'] = data['Power'].fillna(data['Power'].mean())

In [312]:
data['Engine']=data['Engine'].fillna(data['Engine'].mean())

In [313]:
data[['Mileage','Engine','Power']].isna().sum()

Mileage    0
Engine     0
Power      0
dtype: int64

In [314]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Location      7253 non-null   str
 1   Year          7253 non-null   int64
 2   run           7253 non-null   int64
 3   Fuel_Type     7253 non-null   str
 4   Transmission  7253 non-null   str
 5   owner         7253 non-null   str
 6   Mileage       7253 non-null   float64
 7   Engine        7253 non-null   float64
 8   Power         7253 non-null   float64
 9   Seats         7253 non-null   float64
 10  Brand         7253 non-null   str
 11  Model         7253 non-null   str
 12  Engine_class  7253 non-null   str
 13  Power 10%     7078 non-null   float64
dtypes: float64(5), int64(2), str(7)
memory usage: 793.4 KB

In [310]:
data.isna().sum()

Location          0
Year              0
run               0
Fuel_Type         0
Transmission      0
owner             0
Mileage           0
Engine           46
Power             0
Seats             0
Brand             0
Model             0
Engine_class      0
Power 10%       175
dtype: int64

In [311]:
data['Seats']=data['Seats'].fillna(5)

In [244]:
data.isna().sum()

Name                  0
Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               46
Power                46
Seats                 0
dtype: int64

In [245]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2,5.0

In [246]:
# From the column name get brand and model
# first word: brand
# second word: model
data['Name'].str.split()

0                            [Maruti, Wagon, R, LXI, CNG]
1                 [Hyundai, Creta, 1.6, CRDi, SX, Option]
2                                        [Honda, Jazz, V]
3                                   [Maruti, Ertiga, VDI]
4                  [Audi, A4, New, 2.0, TDI, Multitronic]
                              ...
7248               [Volkswagen, Vento, Diesel, Trendline]
7249                          [Volkswagen, Polo, GT, TSI]
7250                          [Nissan, Micra, Diesel, XV]
7251                          [Volkswagen, Polo, GT, TSI]
7252    [Mercedes-Benz, E-Class, 2009-2013, E, 220, CD...
Name: Name, Length: 7253, dtype: object

In [247]:
data['Name'].str.split(' ', expand=True)

,0,1,2,3,4,5,6,7,8,9
0,Maruti,Wagon,R,LXI,CNG,NaN,NaN,NaN,NaN,NaN
1,Hyundai,Creta,1.6,CRDi,SX,Option,NaN,NaN,NaN,NaN
2,Honda,Jazz,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Maruti,Ertiga,VDI,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Audi,A4,New,2.0,TDI,Multitronic,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
7248,Volkswagen,Vento,Diesel,Trendline,NaN,NaN,NaN,NaN,NaN,NaN
7249,Volkswagen,Polo,GT,TSI,NaN,NaN,NaN,NaN,NaN,NaN
7250,Nissan,Micra,Diesel,XV,NaN,NaN,NaN,NaN,NaN,NaN
7251,Volkswagen,Polo,GT,TSI,NaN,NaN,NaN,NaN,NaN,NaN
7252,Mercedes-Benz,E-Class,2009-2013,E,220,CDI,Avantgarde,NaN,NaN,NaN

In [248]:
data['Brand'] = data['Name'].str.split(' ', expand=True)[0]

In [249]:
data['Model'] = data['Name'].str.split(' ', expand=True)[1]

In [250]:
data.head(2)

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2,5.0,Hyundai,Creta

In [251]:
# drop column 'Name'
data.drop('Name', axis= 1, inplace=True)
data.head(2)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2,5.0,Hyundai,Creta

In [252]:
# Replacing values
data.Mileage.min()

np.float64(0.0)

In [253]:
data['Mileage'].agg(['min','max','mean','std'])

min      0.000000
max     33.540000
mean    18.141580
std      4.562197
Name: Mileage, dtype: float64

In [254]:
data[data.Mileage == 0.0]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
14,Pune,2012,85000,Diesel,Automatic,Second,0.0,2179.0,115,5.0,Land,Rover
67,Coimbatore,2019,15369,Diesel,Automatic,First,0.0,1950.0,194,5.0,Mercedes-Benz,C-Class
79,Hyderabad,2005,87591,Petrol,Manual,First,0.0,1086.0,null,5.0,Hyundai,Santro
194,Ahmedabad,2007,60006,Petrol,Manual,First,0.0,NaN,NaN,5.0,Honda,City
229,Bangalore,2015,70436,Diesel,Manual,First,0.0,1498.0,99,5.0,Ford,Figo
...,...,...,...,...,...,...,...,...,...,...,...,...
6633,Kolkata,2016,27000,Diesel,Manual,First,0.0,NaN,NaN,5.0,Mahindra,TUV
6697,Jaipur,2007,85000,Petrol,Manual,Second,0.0,1086.0,null,5.0,Hyundai,Santro
6857,Mumbai,2011,87000,Diesel,Automatic,First,0.0,2179.0,115,5.0,Land,Rover
6957,Kochi,2019,11574,Petrol,Manual,First,0.0,1199.0,88.7,5.0,Honda,Jazz
7226,Ahmedabad,2014,41000,Petrol,Manual,First,0.0,1086.0,62,5.0,Hyundai,Santro

In [255]:
data[data.Mileage==0.0]['Mileage'].value_counts()

Mileage
0.0    81
Name: count, dtype: int64

In [256]:
# replce 0.0 value nearest values
data.sort_values(by='Mileage')['Mileage']

7226     0.00
5647     0.00
707      0.00
6697     0.00
6093     0.00
        ...
2059    33.54
2371    33.54
1332    33.54
4446      NaN
4904      NaN
Name: Mileage, Length: 7253, dtype: float64

In [257]:
data.Mileage.value_counts().sort_index()

Mileage
0.00     81
6.40      1
7.50      1
7.81      1
7.94      3
         ..
30.46     2
31.79     2
32.26     5
33.44     4
33.54     5
Name: count, Length: 438, dtype: int64

In [258]:
# replace 'Mileage' 0.0 values by 6.40 values
data['Mileage'] = data['Mileage'].replace(0.0,6.40)

In [259]:
data.Mileage.min()

np.float64(6.4)

In [260]:
data.isna().sum()

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               2
Engine               46
Power                46
Seats                 0
Brand                 0
Model                 0
dtype: int64

In [261]:
data[data['Mileage'].isna()]

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
4446,Chennai,2016,50000,Electric,Automatic,First,NaN,72.0,41,5.0,Mahindra,E
4904,Mumbai,2011,44000,Electric,Automatic,First,NaN,1798.0,73,5.0,Toyota,Prius

In [262]:
# replace Mileage 'NaN' vlue with mean value
data.Mileage.agg(['min','max','mean'])

min      6.400000
max     33.540000
mean    18.213074
Name: Mileage, dtype: float64

In [263]:
data['Mileage']=data.Mileage.fillna(data['Mileage'].mean())

In [264]:
data.isna().sum()

Location              0
Year                  0
Kilometers_Driven     0
Fuel_Type             0
Transmission          0
Owner_Type            0
Mileage               0
Engine               46
Power                46
Seats                 0
Brand                 0
Model                 0
dtype: int64

In [265]:
data[data['Mileage'].isna()]

Empty DataFrame
Columns: [Location, Year, Kilometers_Driven, Fuel_Type, Transmission, Owner_Type, Mileage, Engine, Power, Seats, Brand, Model]
Index: []

In [266]:
data.head(2)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Brand,Model
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2,5.0,Hyundai,Creta

In [267]:
data.columns

Index(['Location', 'Year', 'Kilometers_Driven', 'Fuel_Type', 'Transmission',
       'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats', 'Brand', 'Model'],
      dtype='str')

In [268]:
# rename columns
data.rename(columns={'Kilometers_Driven':'run','Owner_Type':'owner'}, inplace=True)

In [269]:
data.columns

Index(['Location', 'Year', 'run', 'Fuel_Type', 'Transmission', 'owner',
       'Mileage', 'Engine', 'Power', 'Seats', 'Brand', 'Model'],
      dtype='str')

In [270]:
data.groupby('Location')['Transmission'].value_counts()

Location    Transmission
Ahmedabad   Manual          203
            Automatic        72
Bangalore   Manual          261
            Automatic       179
Chennai     Manual          455
            Automatic       136
Coimbatore  Manual          469
            Automatic       303
Delhi       Manual          456
            Automatic       204
Hyderabad   Manual          644
            Automatic       232
Jaipur      Manual          437
            Automatic        62
Kochi       Manual          527
            Automatic       245
Kolkata     Manual          566
            Automatic        88
Mumbai      Manual          590
            Automatic       359
Pune        Manual          596
            Automatic       169
Name: count, dtype: int64

# Adding column

In [271]:
# add a conditional column, enginetype
data.Engine.agg(['min','max','mean','median'])

min         72.00000
max       5998.00000
mean      1616.57347
median    1493.00000
Name: Engine, dtype: float64

In [272]:
# >='very powerfull', >=1000 'powerfull' , >=500 'less powerfull'
# create funciton
def classify(value):
    if value >=2000:
        return 'Very Powerfull'
    elif value >=1000:
        return 'Powerfull'
    else:
        return 'less Powerfull'

In [289]:
data['Engine'].apply(classify)

0       less Powerfull
1            Powerfull
2            Powerfull
3            Powerfull
4            Powerfull
             ...
7248         Powerfull
7249         Powerfull
7250         Powerfull
7251         Powerfull
7252    Very Powerfull
Name: Engine, Length: 7253, dtype: str

In [290]:
data['Engine_class']=data.Engine.apply(classify)

In [291]:
data.head()

,Location,Year,run,Fuel_Type,Transmission,owner,Mileage,Engine,Power,Seats,Brand,Model,Engine_class
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon,less Powerfull
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta,Powerfull
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,Honda,Jazz,Powerfull
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,Maruti,Ertiga,Powerfull
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,Audi,A4,Powerfull

In [315]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Location      7253 non-null   str
 1   Year          7253 non-null   int64
 2   run           7253 non-null   int64
 3   Fuel_Type     7253 non-null   str
 4   Transmission  7253 non-null   str
 5   owner         7253 non-null   str
 6   Mileage       7253 non-null   float64
 7   Engine        7253 non-null   float64
 8   Power         7253 non-null   float64
 9   Seats         7253 non-null   float64
 10  Brand         7253 non-null   str
 11  Model         7253 non-null   str
 12  Engine_class  7253 non-null   str
 13  Power 10%     7078 non-null   float64
dtypes: float64(5), int64(2), str(7)
memory usage: 793.4 KB

In [316]:
data.Power.dtype

dtype('float64')

In [317]:
# get 10 % of power data
data['Power 10%']=data['Power']*0.1

In [318]:
data.head()

,Location,Year,run,Fuel_Type,Transmission,owner,Mileage,Engine,Power,Seats,Brand,Model,Engine_class,Power 10%
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon,less Powerfull,5.816
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta,Powerfull,12.620
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,Honda,Jazz,Powerfull,8.870
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,Maruti,Ertiga,Powerfull,8.876
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,Audi,A4,Powerfull,14.080

In [319]:
data

,Location,Year,run,Fuel_Type,Transmission,owner,Mileage,Engine,Power,Seats,Brand,Model,Engine_class,Power 10%
0,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16,5.0,Maruti,Wagon,less Powerfull,5.816
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.20,5.0,Hyundai,Creta,Powerfull,12.620
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.70,5.0,Honda,Jazz,Powerfull,8.870
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76,7.0,Maruti,Ertiga,Powerfull,8.876
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.80,5.0,Audi,A4,Powerfull,14.080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7248,Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598.0,103.60,5.0,Volkswagen,Vento,Powerfull,10.360
7249,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.60,5.0,Volkswagen,Polo,Powerfull,10.360
7250,Kolkata,2012,28000,Diesel,Manual,First,23.08,1461.0,63.10,5.0,Nissan,Micra,Powerfull,6.310
7251,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.60,5.0,Volkswagen,Polo,Powerfull,10.360
7252,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170.00,5.0,Mercedes-Benz,E-Class,Very Powerfull,17.000

In [320]:
data['Power 10%'].value_counts()

Power 10%
7.400000     280
11.276521    175
9.860000     166
7.390000     152
14.000000    142
            ...
25.200000      1
32.850000      1
9.863000       1
36.000000      1
24.160000      1
Name: count, Length: 384, dtype: int64

In [321]:
data.isna().sum()

Location        0
Year            0
run             0
Fuel_Type       0
Transmission    0
owner           0
Mileage         0
Engine          0
Power           0
Seats           0
Brand           0
Model           0
Engine_class    0
Power 10%       0
dtype: int64

# Aggregation

In [322]:
# aggregation function for finding summary of data
data['Mileage'].sum()

np.float64(132099.42614811752)

In [323]:
data['Mileage'].max()

np.float64(33.54)

In [324]:
data['Mileage'].agg(['min','max','mean','std','median'])

min        6.400000
max       33.540000
mean      18.213074
std        4.320489
median    18.160000
Name: Mileage, dtype: float64

In [328]:
data[['Mileage','Engine','Power']].agg(['min','max','mean','std','var'])

        Mileage         Engine        Power
min    6.400000      72.000000    34.200000
max   33.540000    5998.000000   616.000000
mean  18.213074    1616.573470   112.765214
std    4.320489     593.394164    52.844178
var   18.666627  352116.633321  2792.507133

In [326]:
data[['Mileage','Engine','Power']].describe()

           Mileage       Engine        Power
count  7253.000000  7253.000000  7253.000000
mean     18.213074  1616.573470   112.765214
std       4.320489   593.394164    52.844178
min       6.400000    72.000000    34.200000
25%      15.170000  1198.000000    77.000000
50%      18.160000  1493.000000    98.600000
75%      21.100000  1968.000000   138.030000
max      33.540000  5998.000000   616.000000

In [327]:
data['Mileage'].var()

np.float64(18.66662732752764)

# Group bY

In [330]:
data.Mileage.max()

np.float64(33.54)

In [331]:
data.Location.nunique()

11

In [332]:
# find the max mileage of each location
data.groupby('Location')['Mileage'].max()

Location
Ahmedabad     28.40
Bangalore     28.09
Chennai       28.40
Coimbatore    28.40
Delhi         33.54
Hyderabad     28.40
Jaipur        28.40
Kochi         33.44
Kolkata       30.46
Mumbai        33.54
Pune          33.54
Name: Mileage, dtype: float64

In [334]:
# find the min mileage values of each brand
data.Brand.nunique()

33

In [335]:
data.groupby('Brand')['Mileage'].min()

Brand
Ambassador       12.80
Audi              6.40
BMW               7.94
Bentley           8.60
Chevrolet        11.50
Datsun           19.44
Fiat              6.40
Force            17.00
Ford              6.40
Hindustan        14.10
Honda             6.40
Hyundai           6.40
ISUZU            12.40
Isuzu            12.08
Jaguar            9.43
Jeep             16.00
Lamborghini       6.40
Land              6.40
Mahindra          6.40
Maruti            6.40
Mercedes-Benz     6.40
Mini             13.60
Mitsubishi        9.50
Nissan            9.10
OpelCorsa        14.20
Porsche           7.50
Renault          13.06
Skoda             6.40
Smart             6.40
Tata             11.57
Toyota            6.40
Volkswagen        6.40
Volvo             9.00
Name: Mileage, dtype: float64

In [337]:
# group by location, brand, min mileage
# multiple grouping
data.groupby(['Location','Brand'])['Mileage'].min()

Location   Brand
Ahmedabad  Audi           9.74
           BMW           11.50
           Chevrolet     17.80
           Ford          20.00
           Honda          6.40
                         ...
Pune       Smart          6.40
           Tata          12.85
           Toyota         6.40
           Volkswagen    14.40
           Volvo         13.50
Name: Mileage, Length: 261, dtype: float64

In [339]:
# for each location,for each brand, for each transmission find the minimum mileage
data.groupby(['Location','Brand','Transmission'])['Mileage'].min()

Location   Brand       Transmission
Ahmedabad  Audi        Automatic        9.74
           BMW         Automatic       11.50
           Chevrolet   Automatic       18.10
                       Manual          17.80
           Ford        Manual          20.00
                                       ...
Pune       Toyota      Automatic       11.00
                       Manual           6.40
           Volkswagen  Automatic       14.40
                       Manual          15.04
           Volvo       Automatic       13.50
Name: Mileage, Length: 398, dtype: float64

In [341]:
# group by with multiple aggregation
# find max value of mileage, engine, power according to location
data.groupby('Location')[['Mileage','Engine','Power']].max()

            Mileage  Engine   Power
Location
Ahmedabad     28.40  2993.0  308.43
Bangalore     28.09  5998.0  616.00
Chennai       28.40  3200.0  308.43
Coimbatore    28.40  5000.0  503.00
Delhi         33.54  5204.0  560.00
Hyderabad     28.40  5998.0  552.00
Jaipur        28.40  3198.0  265.00
Kochi         33.44  4951.0  450.00
Kolkata       30.46  5461.0  387.30
Mumbai        33.54  4806.0  550.00
Pune          33.54  3498.0  321.00

In [343]:
df=data.groupby('Location')[['Mileage','Engine','Power']].agg(['min','max','mean','median','std','var'])

In [344]:
df.head()

           Mileage                                               Engine  \
               min    max       mean median       std        var    min
Location
Ahmedabad      6.4  28.40  18.893018  18.90  4.825665  23.287044  624.0
Bangalore      6.4  28.09  16.931955  17.00  4.260510  18.151945  624.0
Chennai        6.4  28.40  18.106300  18.20  4.237389  17.955470   72.0
Coimbatore     6.4  28.40  17.964508  18.16  3.996333  15.970677  624.0
Delhi          6.4  33.54  17.937061  17.69  4.608770  21.240762  624.0

                                                                    Power  \
               max         mean  median         std            var    min
Location
Ahmedabad   2993.0  1582.587540  1495.0  508.248752  258316.793409  37.48
Bangalore   5998.0  1811.067245  1598.0  700.743888  491041.996388  34.20
Chennai     3200.0  1613.017169  1461.0  574.057335  329541.824348  35.50
Coimbatore  5000.0  1694.899154  1498.0  658.591994  433743.414514  34.20
Delhi       5204.0  1709.210405  1498.0  625.214320  390892.945521  37.48


               max        mean median        std          var
Location
Ahmedabad   308.43  110.509167   98.6  45.356639  2057.224703
Bangalore   616.00  132.124883  117.3  63.995474  4095.420629
Chennai     308.43  106.946378   90.0  46.388209  2151.865980
Coimbatore  503.00  123.515184  103.5  61.157407  3740.228471
Delhi       560.00  120.215140  106.1  54.043651  2920.716196

In [345]:
# export 'df' dataset to csv file
df.to_csv('location_mileage_perf.csv',index=False)

In [ ]:
# Pivot tabel -- summary tables, more interactive
# multi-indexing ---to find the records uniquely and fast from the large data set
# merge, join , concatenate