In [1]:
# load dataset
# explore dataset
# indexing and filtering
# sorting
# column drop, rename, arrange

In [2]:
import pandas as pd

In [3]:
data = pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\used_cars_data_uncleaned.csv")
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [4]:
# explore dataset

In [5]:
data.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [6]:
data.tail(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2,1197.0,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0,2148.0,170 bhp,5.0,NaN,NaN

In [7]:
# dataset structure
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7251 non-null   float64
 9   Engine             7207 non-null   float64
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(4), int64(3), str(7)
memory usage: 793.4 KB

In [8]:
# statistical values
data.describe()

,S.No.,Year,Kilometers_Driven,Mileage,Engine,Seats,Price
count,7253.000000,7253.000000,7.253000e+03,7251.000000,7207.000000,7200.000000,6019.000000
mean,3626.000000,2013.365366,5.869906e+04,18.141580,1616.573470,5.279722,9.479468
std,2093.905084,3.254421,8.442772e+04,4.562197,595.285137,0.811660,11.187917
min,0.000000,1996.000000,1.710000e+02,0.000000,72.000000,0.000000,0.440000
25%,1813.000000,2011.000000,3.400000e+04,15.170000,1198.000000,5.000000,3.500000
50%,3626.000000,2014.000000,5.341600e+04,18.160000,1493.000000,5.000000,5.640000
75%,5439.000000,2016.000000,7.300000e+04,21.100000,1968.000000,5.000000,9.950000
max,7252.000000,2019.000000,6.500000e+06,33.540000,5998.000000,10.000000,160.000000

In [9]:
# check null values
data.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [10]:
# check columns
data.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [13]:
# check count values
data.value_counts(['Name'])

Name
Mahindra XUV500 W8 2WD                55
Maruti Swift VDI                      49
Maruti Swift Dzire VDI                42
Honda City 1.5 S MT                   39
Maruti Swift VDI BSIV                 37
                                      ..
Skoda Superb Petrol Ambition           1
Tata Tiago 1.05 Revotorq XT Option     1
Ford EcoSport 1.5 Petrol Ambiente      1
Jeep Compass 1.4 Sport                 1
Hyundai Elite i20 Magna Plus           1
Name: count, Length: 2041, dtype: int64

In [14]:
data.shape

(7253, 14)

In [15]:
data.ndim

2

# indexing and filtering

In [16]:
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [17]:
# loc() and iloc()
# loc() -- use index and column name

In [18]:
# get first 5 rows and first 5 columns using iloc()
data.iloc[0:5,0:5]

,S.No.,Name,Location,Year,Kilometers_Driven
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000
2,2,Honda Jazz V,Chennai,2011,46000
3,3,Maruti Ertiga VDI,Chennai,2012,87000
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670

In [19]:
# get index 40 to 45 rows and columns 'Name','Engine' only using loc
data.loc[40:45,['Name','Engine']]

                                         Name  Engine
40                            Maruti Alto LXi   796.0
41                            Tata Nano LX SE   624.0
42  Mahindra KUV 100 mFALCON D75 K8 Dual Tone  1198.0
43             Hyundai i20 Magna Optional 1.2  1197.0
44           Hyundai Elantra 2.0 SX Option AT  1999.0
45                  Toyota Corolla Altis G AT  1798.0

In [21]:
# get last three rows and three columns
data.iloc[-1:-4:-1,0:3]

      S.No.                                               Name Location
7252   7252  Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...    Kochi
7251   7251                             Volkswagen Polo GT TSI     Pune
7250   7250                             Nissan Micra Diesel XV  Kolkata

In [22]:
# get rows from 10 to 30 in step 3 and column 5 to 10
data.iloc[10:30:3, 5:10]

   Fuel_Type Transmission Owner_Type  Mileage  Engine
10    Petrol       Manual      First    21.56  1462.0
13    Diesel    Automatic      First    12.70  2179.0
16    Diesel       Manual      First    25.80  1498.0
19    Diesel    Automatic      First    14.84  2143.0
22    Petrol    Automatic      First    13.53  1984.0
25    Petrol       Manual      First    16.80  1497.0
28    Petrol       Manual      First    17.50  1199.0

In [23]:
data['Name'].head()

0              Maruti Wagon R LXI CNG
1    Hyundai Creta 1.6 CRDi SX Option
2                        Honda Jazz V
3                   Maruti Ertiga VDI
4     Audi A4 New 2.0 TDI Multitronic
Name: Name, dtype: str

In [25]:
data[['Name','Year']]

                                                   Name  Year
0                                Maruti Wagon R LXI CNG  2010
1                      Hyundai Creta 1.6 CRDi SX Option  2015
2                                          Honda Jazz V  2011
3                                     Maruti Ertiga VDI  2012
4                       Audi A4 New 2.0 TDI Multitronic  2013
...                                                 ...   ...
7248                  Volkswagen Vento Diesel Trendline  2011
7249                             Volkswagen Polo GT TSI  2015
7250                             Nissan Micra Diesel XV  2012
7251                             Volkswagen Polo GT TSI  2013
7252  Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...  2014

[7253 rows x 2 columns]

In [26]:
data.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [27]:
# get Mileage >=30
con1 = data['Mileage']>=30
data[con1]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
2701,2701,Maruti Celerio CNG VXI MT,Kochi,2016,70536,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,4.58
3119,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,4.00
3129,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.35 Lakh,3.25
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
3869,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.3 bhp,4.0,NaN,2.10
4141,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,2.85
4769,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.70
5178,5178,Maruti Celerio CNG VXI MT,Delhi,2015,64687,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,3.80
5710,5710,Maruti Alto 800 CNG LXI,Mumbai,2013,26200,CNG,Manual,First,30.46,796.0,47.3 bhp,5.0,NaN,2.15
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
6019,6019,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6538,6538,Maruti Alto K10 LXI CNG,Kochi,2015,47490,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6788,6788,Maruti Alto K10 LXI CNG Optional,Delhi,2017,33000,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,NaN
6958,6958,Maruti Alto 800 CNG LXI,Kolkata,2013,14311,CNG,Manual,First,30.46,796.0,47.3 bhp,5.0,NaN,NaN

In [29]:
# get Mileage >=32 and Transmission is manual
con1 = data['Mileage']>=32
con2 = data['Transmission']=='Manual'
data[con1 & con2]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
3119,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,4.00
3129,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.35 Lakh,3.25
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
3869,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.3 bhp,4.0,NaN,2.10
4141,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,2.85
4769,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.70
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
6019,6019,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6538,6538,Maruti Alto K10 LXI CNG,Kochi,2015,47490,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6788,6788,Maruti Alto K10 LXI CNG Optional,Delhi,2017,33000,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,NaN

In [34]:
data[(data['Mileage']>=32) & (data['Transmission']=='Manual')]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
3119,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,4.00
3129,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.35 Lakh,3.25
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
3869,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.3 bhp,4.0,NaN,2.10
4141,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,2.85
4769,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.70
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
6019,6019,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6538,6538,Maruti Alto K10 LXI CNG,Kochi,2015,47490,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6788,6788,Maruti Alto K10 LXI CNG Optional,Delhi,2017,33000,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,NaN

In [35]:
data[con1 & con2][['Name','Year']]

                                   Name  Year
1269  Maruti Alto 800 2016-2019 CNG LXI  2018
1332             Maruti Wagon R CNG LXI  2013
2059             Maruti Wagon R CNG LXI  2013
2371             Maruti Wagon R CNG LXI  2014
3119   Maruti Alto K10 LXI CNG Optional  2018
3129             Maruti Wagon R CNG LXI  2014
3553  Maruti Alto 800 2016-2019 CNG LXI  2015
3869  Maruti Alto 800 2016-2019 CNG LXI  2012
4141             Maruti Wagon R CNG LXI  2014
4769  Maruti Alto 800 2016-2019 CNG LXI  2017
5935            Maruti Alto K10 LXI CNG  2015
6019            Maruti Alto K10 LXI CNG  2014
6538            Maruti Alto K10 LXI CNG  2015
6788   Maruti Alto K10 LXI CNG Optional  2017

In [36]:
data.sample(n=10) # generate 10 rows randomly

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
108,108,Mahindra XUV500 W8 2WD,Delhi,2012,65000,Diesel,Manual,Second,16.00,2179.0,140 bhp,7.0,NaN,5.75
2112,2112,Hyundai Creta 1.6 CRDi SX,Jaipur,2015,83950,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,9.95
4574,4574,Hyundai Creta 1.6 CRDi SX Option,Bangalore,2016,51000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,13.25
497,497,Maruti Zen LXi BSII,Chennai,2004,29000,Petrol,Manual,First,17.30,993.0,60 bhp,5.0,NaN,1.60
1419,1419,Hyundai Santro Xing XL,Chennai,2007,82000,Petrol,Manual,Second,0.00,1086.0,null bhp,5.0,NaN,1.35
5928,5928,Mahindra NuvoSport N6,Coimbatore,2018,37323,Diesel,Manual,Second,17.45,1493.0,100 bhp,7.0,10.52 Lakh,7.29
7183,7183,Hyundai Verna CRDi SX,Hyderabad,2009,137711,Diesel,Manual,First,16.80,1493.0,110 bhp,5.0,NaN,NaN
6208,6208,Audi Q5 2008-2012 2.0 TDI,Coimbatore,2012,94049,Diesel,Automatic,First,12.80,1968.0,167.6 bhp,5.0,NaN,NaN
1056,1056,Maruti S-Cross Zeta DDiS 200 SH,Coimbatore,2016,74611,Diesel,Manual,First,25.10,1248.0,88.5 bhp,5.0,13.26 Lakh,7.94
5262,5262,Tata Tiago 1.2 Revotron XM Option,Chennai,2016,5400,Petrol,Manual,First,23.84,1199.0,84 bhp,5.0,5.45 Lakh,3.98

In [37]:
data.sample(frac=0.01) # generate 1 % of total records

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
4764,4764,Hyundai EON D Lite Plus,Coimbatore,2016,64624,Petrol,Manual,First,21.10,814.0,55.2 bhp,5.0,NaN,3.71
5954,5954,Toyota Fortuner 4x4 AT,Chennai,2015,95000,Diesel,Automatic,First,12.55,2982.0,168.5 bhp,7.0,NaN,19.60
5326,5326,Hyundai i20 1.2 Asta Option,Bangalore,2016,19000,Petrol,Manual,First,18.60,1197.0,81.83 bhp,5.0,NaN,7.25
5405,5405,Audi Q7 3.0 TDI Quattro Premium Plus,Delhi,2014,58000,Diesel,Automatic,First,12.07,2967.0,241.4 bhp,7.0,NaN,32.00
1982,1982,Honda A ord 2.4 A/T,Mumbai,2011,54774,Petrol,Automatic,First,11.70,2354.0,177.6 bhp,5.0,NaN,6.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2784,2784,Nissan Micra Diesel XV,Hyderabad,2011,86732,Diesel,Manual,First,23.08,1461.0,63.1 bhp,5.0,NaN,3.60
470,470,Maruti Ciaz 1.3 S,Coimbatore,2017,25142,Diesel,Manual,First,28.09,1248.0,88.5 bhp,5.0,NaN,8.26
696,696,Volkswagen Passat Highline DSG,Kolkata,2012,39273,Diesel,Automatic,First,14.30,1968.0,140 bhp,5.0,NaN,6.99
6319,6319,Maruti Zen Estilo LXI BS IV,Pune,2010,70000,Petrol,Manual,Second,19.00,998.0,67.1 bhp,5.0,NaN,NaN
4963,4963,Maruti Swift Vdi BSIII,Jaipur,2010,152000,Diesel,Manual,First,17.80,1248.0,75 bhp,5.0,NaN,2.90

In [38]:
data.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [39]:
data['Name'].unique()

<StringArray>
[                 'Maruti Wagon R LXI CNG',
        'Hyundai Creta 1.6 CRDi SX Option',
                            'Honda Jazz V',
                       'Maruti Ertiga VDI',
         'Audi A4 New 2.0 TDI Multitronic',
         'Hyundai EON LPG Era Plus Option',
                  'Nissan Micra Diesel XV',
       'Toyota Innova Crysta 2.8 GX AT 8S',
     'Volkswagen Vento Diesel Comfortline',
          'Tata Indica Vista Quadrajet LS',
 ...
   'Mercedes-Benz S Class 2005 2013 320 L',
                       'Maruti Alto XCITE',
 'Land Rover Discovery 4 TDV6 Auto Diesel',
 'Hyundai Verna Transform VTVT with Audio',
       'Maruti Vitara Brezza ZDi Plus AMT',
            'Skoda Superb Petrol Ambition',
      'Tata Tiago 1.05 Revotorq XT Option',
       'Ford EcoSport 1.5 Petrol Ambiente',
                  'Jeep Compass 1.4 Sport',
            'Hyundai Elite i20 Magna Plus']
Length: 2041, dtype: str

In [40]:
data['Name'].nunique()

2041

In [41]:
data.Transmission.unique()

<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

In [42]:
data.Transmission.nunique()

2

In [43]:
data[data['Transmission']=='Automatic']

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755.0,171.5 bhp,8.0,21 Lakh,17.50
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.80,1497.0,116.3 bhp,5.0,NaN,4.49
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.70,2179.0,187.7 bhp,5.0,NaN,27.00
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.00,2179.0,115 bhp,5.0,NaN,17.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7241,7241,BMW 5 Series 525d Sedan,Delhi,2012,80000,Diesel,Automatic,First,16.73,2993.0,218 bhp,5.0,NaN,NaN
7246,7246,Hyundai Grand i10 AT Asta,Coimbatore,2016,18242,Petrol,Automatic,First,18.90,1197.0,82 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.6 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170 bhp,5.0,NaN,NaN

In [44]:
data.Location.nunique()

11

In [46]:
data.Location.unique()

<StringArray>
[    'Mumbai',       'Pune',    'Chennai', 'Coimbatore',  'Hyderabad',
     'Jaipur',      'Kochi',    'Kolkata',      'Delhi',  'Bangalore',
  'Ahmedabad']
Length: 11, dtype: str

In [47]:
data['Location'].value_counts()

Location
Mumbai        949
Hyderabad     876
Coimbatore    772
Kochi         772
Pune          765
Delhi         660
Kolkata       654
Chennai       591
Jaipur        499
Bangalore     440
Ahmedabad     275
Name: count, dtype: int64

In [48]:
data[data.Location=='Pune']

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.5
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54,1598.0,103.6 bhp,5.0,NaN,5.2
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.00,2179.0,115 bhp,5.0,NaN,17.5
38,38,Mercedes-Benz M-Class ML 350 CDI,Pune,2013,85000,Diesel,Automatic,First,11.74,2987.0,254.8 bhp,5.0,NaN,28.0
63,63,Mercedes-Benz New C-Class 200 CDI Classic,Pune,2011,65000,Diesel,Manual,Second,15.80,2148.0,170 bhp,5.0,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7200,7200,Maruti Ritz LDi,Pune,2015,190000,Diesel,Manual,First,23.20,1248.0,73.94 bhp,5.0,NaN,NaN
7228,7228,Tata Tiago 1.05 Revotorq XT Option,Pune,2016,41413,Diesel,Manual,First,27.28,1047.0,69 bhp,5.0,7.06 Lakh,NaN
7230,7230,Hyundai i20 1.2 Spotz,Pune,2014,30315,Petrol,Manual,First,18.60,1197.0,81.83 bhp,5.0,NaN,NaN
7244,7244,Chevrolet Aveo 1.4 LS,Pune,2009,45463,Petrol,Manual,First,14.49,1399.0,92.7 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.6 bhp,5.0,NaN,NaN

In [49]:
# get not manual
data[data.Transmission !='Manual']

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755.0,171.5 bhp,8.0,21 Lakh,17.50
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.80,1497.0,116.3 bhp,5.0,NaN,4.49
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.70,2179.0,187.7 bhp,5.0,NaN,27.00
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.00,2179.0,115 bhp,5.0,NaN,17.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7241,7241,BMW 5 Series 525d Sedan,Delhi,2012,80000,Diesel,Automatic,First,16.73,2993.0,218 bhp,5.0,NaN,NaN
7246,7246,Hyundai Grand i10 AT Asta,Coimbatore,2016,18242,Petrol,Automatic,First,18.90,1197.0,82 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.6 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170 bhp,5.0,NaN,NaN

In [52]:
data[data['Transmission']!='Manual'].Transmission.value_counts()

Transmission
Automatic    2049
Name: count, dtype: int64

In [62]:
data[data['Transmission']!='Manual'].Transmission.value_counts()

Transmission
Automatic    2049
Name: count, dtype: int64

In [63]:
data.Transmission.value_counts()

Transmission
Manual       5204
Automatic    2049
Name: count, dtype: int64

# Sorting

In [64]:
data.sort_values(by='Name')

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1221,1221,Ambassador Classic Nova Diesel,Chennai,2003,80000,Diesel,Manual,Third,12.80,1489.0,35.5 bhp,5.0,NaN,1.35
6663,6663,Audi A3 35 TDI Attraction,Ahmedabad,2014,84004,Diesel,Automatic,First,20.38,1968.0,143 bhp,5.0,NaN,NaN
398,398,Audi A3 35 TDI Attraction,Chennai,2014,79271,Diesel,Automatic,First,20.38,1968.0,143 bhp,5.0,NaN,16.50
4782,4782,Audi A3 35 TDI Premium,Mumbai,2016,20003,Diesel,Automatic,First,20.38,1968.0,143 bhp,5.0,NaN,19.25
6742,6742,Audi A3 35 TDI Premium Plus,Hyderabad,2015,52300,Diesel,Automatic,First,20.38,1968.0,143 bhp,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1178,1178,Volvo XC60 D5 Inscription,Kochi,2014,86925,Diesel,Automatic,First,11.20,2400.0,215 bhp,5.0,NaN,17.18
4497,4497,Volvo XC90 2007-2015 D5 AT AWD,Kochi,2014,102001,Diesel,Automatic,First,11.10,2400.0,200 bhp,7.0,NaN,23.58
6384,6384,Volvo XC90 2007-2015 D5 AWD,Bangalore,2016,70000,Diesel,Manual,First,11.10,2400.0,200 bhp,7.0,NaN,NaN
2401,2401,Volvo XC90 2007-2015 D5 AWD,Kochi,2014,89230,Diesel,Manual,First,11.10,2400.0,200 bhp,7.0,NaN,23.65
6659,6659,Volvo XC90 2007-2015 D5 AWD,Delhi,2014,22230,Diesel,Manual,First,11.10,2400.0,200 bhp,7.0,NaN,NaN

In [65]:
data.sort_values(by='Transmission')

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170 bhp,5.0,NaN,NaN
5595,5595,BMW 5 Series 2013-2017 520d Luxury Line,Jaipur,2013,40714,Diesel,Automatic,Second,18.12,1995.0,190 bhp,5.0,NaN,24.75
2355,2355,Mercedes-Benz GLA Class 200 Sport Edition,Delhi,2016,23000,Petrol,Automatic,First,13.70,1991.0,183 bhp,5.0,NaN,25.00
2357,2357,Mercedes-Benz CLA 200 Sport Edition,Delhi,2016,25000,Petrol,Automatic,First,15.04,1991.0,183 bhp,5.0,NaN,26.00
5587,5587,BMW X1 sDrive 20d Sportline,Kolkata,2013,56683,Diesel,Automatic,Second,17.05,1995.0,184 bhp,5.0,NaN,13.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2836,2836,Tata Indigo CS eVX,Chennai,2015,100073,Diesel,Manual,Second,25.00,1396.0,69.01 bhp,5.0,NaN,2.00
2834,2834,Maruti Swift VDI BSIV,Chennai,2015,23000,Diesel,Manual,First,25.20,1248.0,74 bhp,5.0,NaN,6.50
2832,2832,Tata Zest Quadrajet 1.3,Kochi,2016,54199,Diesel,Manual,First,23.00,1248.0,88.8 bhp,5.0,NaN,5.00
2848,2848,Maruti Wagon R LXI BS IV,Delhi,2014,65694,Petrol,Manual,First,18.90,998.0,67.1 bhp,5.0,NaN,3.25
3626,3626,Ford Figo Diesel ZXI,Coimbatore,2015,92885,Diesel,Manual,First,20.00,1399.0,68 bhp,5.0,NaN,3.56

In [66]:
# multilevel sorting
data.sort_values(by=['Location','Mileage'])

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
194,194,Honda City 1.5 GXI,Ahmedabad,2007,60006,Petrol,Manual,First,0.00,NaN,NaN,NaN,NaN,2.95
3061,3061,Hyundai Santro GS,Ahmedabad,2005,58000,Petrol,Manual,Second,0.00,999.0,null bhp,5.0,NaN,1.51
5374,5374,Mercedes-Benz M-Class ML 350 4Matic,Ahmedabad,2012,66000,Diesel,Automatic,First,0.00,2987.0,165 bhp,5.0,NaN,23.00
5875,5875,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,2019,4000,Diesel,Automatic,First,0.00,1950.0,194 bhp,5.0,49.14 Lakh,35.00
6090,6090,Hyundai Santro Xing GL,Ahmedabad,2013,63831,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5940,5940,Maruti Dzire LDI,Pune,2018,27000,Diesel,Manual,First,28.40,1248.0,73.75 bhp,5.0,7.91 Lakh,5.90
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90

In [67]:
data.sort_values(by=['Location','Mileage'], ascending=False)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
1756,1756,Maruti Swift DDiS VDI,Pune,2008,150000,Diesel,Manual,Second,28.40,1248.0,74 bhp,5.0,NaN,2.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,5374,Mercedes-Benz M-Class ML 350 4Matic,Ahmedabad,2012,66000,Diesel,Automatic,First,0.00,2987.0,165 bhp,5.0,NaN,23.00
5875,5875,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,2019,4000,Diesel,Automatic,First,0.00,1950.0,194 bhp,5.0,49.14 Lakh,35.00
6090,6090,Hyundai Santro Xing GL,Ahmedabad,2013,63831,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN
6205,6205,Hyundai Santro Xing GL,Ahmedabad,2007,78000,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN
7226,7226,Hyundai Santro Xing GL,Ahmedabad,2014,41000,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN

In [70]:
data.sort_values(by=['Location','Year'])[['Name','Location']]

                                        Name   Location
1318                      Honda City 1.3 EXI  Ahmedabad
3200                 Maruti Wagon R LX BSIII  Ahmedabad
3061                       Hyundai Santro GS  Ahmedabad
5843               Maruti Esteem Vxi - BSIII  Ahmedabad
194                       Honda City 1.5 GXI  Ahmedabad
...                                      ...        ...
5940                        Maruti Dzire LDI       Pune
5941                        Renault KWID RXL       Pune
6155          Jaguar XE 2.0L Diesel Prestige       Pune
5339  Hyundai i20 Active SX Dual Tone Petrol       Pune
6529                       Honda Jazz VX CVT       Pune

[7253 rows x 2 columns]

In [71]:
data.Mileage.value_counts()

Mileage
17.00    208
18.90    201
18.60    144
21.10    107
20.36    105
        ...
20.80      1
11.88      1
12.08      1
15.56      1
17.15      1
Name: count, Length: 438, dtype: int64

In [72]:
data.Fuel_Type.unique()

<StringArray>
['CNG', 'Diesel', 'Petrol', 'LPG', 'Electric']
Length: 5, dtype: str

In [73]:
data.Fuel_Type.nunique()

5

In [74]:
data.Fuel_Type.value_counts()

Fuel_Type
Diesel      3852
Petrol      3325
CNG           62
LPG           12
Electric       2
Name: count, dtype: int64

In [75]:
data.Mileage.min()

np.float64(0.0)

In [76]:
data.Mileage.max()

np.float64(33.54)

In [77]:
data.Mileage.mean()

np.float64(18.141580471659083)

In [78]:
data.Mileage.std()

np.float64(4.562196601725892)

In [79]:
data.Mileage.median()

np.float64(18.16)

In [80]:
data.Mileage.quantile(0.25)

np.float64(15.17)

In [81]:
data.Mileage.quantile(0.75)

np.float64(21.1)

In [82]:
data.Mileage.sum()

np.float64(131544.6)

# column rename, drop , arrange

In [83]:
data.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [84]:
data.drop('S.No.', axis=1, inplace=True)

In [85]:
data.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [87]:
data.drop(columns=['Power','Seats'], inplace=True)

In [88]:
data.columns

Index(['Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'New_Price',
       'Price'],
      dtype='str')

In [89]:
data.rename(columns={'Kilometers_Driven':'distance','Fuel_Type':'fule','New_Price':'price'}, inplace=True)

In [90]:
data.columns

Index(['Name', 'Location', 'Year', 'distance', 'fule', 'Transmission',
       'Owner_Type', 'Mileage', 'Engine', 'price', 'Price'],
      dtype='str')

In [91]:
# rearrange column
col = ['Year','Location','Name','distance', 'fule', 'Transmission',
       'Owner_Type', 'Mileage', 'Engine', 'price', 'Price']

In [92]:
data = data[col]

In [ ]:
# save data
data.to_csv('saveddata.csv',inde