# Pandas

Series and dataFarme
Loading datasets (csv, excel)
Exploring data (head, info, describe)
INdexing and filtering
Sorting data

In [1]:
pip install pandas

Collecting pandas
  Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Using cached numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\venv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# import pandas
import pandas as pd

# pandas data strucute
# Series, DataFrame, Panel
Series - one d array, pd.Series()
DataFrame -- 2 D array, pd.DataFrame()
Panel - 3 D array , pd.Panel()

In [4]:
# series
pd.Series(range(2,24,3))

0     2
1     5
2     8
3    11
4    14
5    17
6    20
7    23
dtype: int64

In [5]:
# DataFrame
pd.DataFrame(range(1,24,3))

    0
0   1
1   4
2   7
3  10
4  13
5  16
6  19
7  22

# loading data

In [127]:
# loading csv file
df=pd.read_csv(r"D:\my project\codeit_datascience\data_science\regression\data science\used_cars_data_uncleaned.csv")
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

# Preview the data or Exploring data

In [11]:
# exploring head,tail, info, describe

In [12]:
df.head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [13]:
df.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [14]:
df.tail()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7248,7248,Volkswagen Vento Diesel Trendline,Hyderabad,2011,89411,Diesel,Manual,First,20.54,1598.0,103.6 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.6 bhp,5.0,NaN,NaN
7250,7250,Nissan Micra Diesel XV,Kolkata,2012,28000,Diesel,Manual,First,23.08,1461.0,63.1 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170 bhp,5.0,NaN,NaN

In [15]:
df.tail(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.2,1197.0,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.0,2148.0,170 bhp,5.0,NaN,NaN

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7253 entries, 0 to 7252
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   S.No.              7253 non-null   int64
 1   Name               7253 non-null   str
 2   Location           7253 non-null   str
 3   Year               7253 non-null   int64
 4   Kilometers_Driven  7253 non-null   int64
 5   Fuel_Type          7253 non-null   str
 6   Transmission       7253 non-null   str
 7   Owner_Type         7253 non-null   str
 8   Mileage            7251 non-null   float64
 9   Engine             7207 non-null   float64
 10  Power              7207 non-null   str
 11  Seats              7200 non-null   float64
 12  New_Price          1006 non-null   str
 13  Price              6019 non-null   float64
dtypes: float64(4), int64(3), str(7)
memory usage: 793.4 KB

In [17]:
df.describe()

,S.No.,Year,Kilometers_Driven,Mileage,Engine,Seats,Price
count,7253.000000,7253.000000,7.253000e+03,7251.000000,7207.000000,7200.000000,6019.000000
mean,3626.000000,2013.365366,5.869906e+04,18.141580,1616.573470,5.279722,9.479468
std,2093.905084,3.254421,8.442772e+04,4.562197,595.285137,0.811660,11.187917
min,0.000000,1996.000000,1.710000e+02,0.000000,72.000000,0.000000,0.440000
25%,1813.000000,2011.000000,3.400000e+04,15.170000,1198.000000,5.000000,3.500000
50%,3626.000000,2014.000000,5.341600e+04,18.160000,1493.000000,5.000000,5.640000
75%,5439.000000,2016.000000,7.300000e+04,21.100000,1968.000000,5.000000,9.950000
max,7252.000000,2019.000000,6.500000e+06,33.540000,5998.000000,10.000000,160.000000

In [18]:
df.isna().sum()

S.No.                   0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 46
Power                  46
Seats                  53
New_Price            6247
Price                1234
dtype: int64

In [19]:
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [20]:
# shape - return rows and column number
df.shape

(7253, 14)

In [21]:
df.ndim

2

In [27]:
# Indexing and filtering
# iloc -- only numeric e.g df.iloc[row index, column index]
# loc --label e.g df.loc[row index, column name] e.g df.loc[index label, column name]
df.iloc[0:5] # using index and filter first 5 rows and all columsn

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [24]:
# filter first 5 rows and first 5 columns only
df.iloc[0:5,0:5]

,S.No.,Name,Location,Year,Kilometers_Driven
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000
2,2,Honda Jazz V,Chennai,2011,46000
3,3,Maruti Ertiga VDI,Chennai,2012,87000
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670

In [26]:
df.loc[0:3,'Name']

0              Maruti Wagon R LXI CNG
1    Hyundai Creta 1.6 CRDi SX Option
2                        Honda Jazz V
3                   Maruti Ertiga VDI
Name: Name, dtype: str

In [28]:
df.loc[0:6:2, ['Name','Location','Year']]

                              Name    Location  Year
0           Maruti Wagon R LXI CNG      Mumbai  2010
2                     Honda Jazz V     Chennai  2011
4  Audi A4 New 2.0 TDI Multitronic  Coimbatore  2013
6           Nissan Micra Diesel XV      Jaipur  2013

In [29]:
df.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [30]:
# indexing is the process of selecting data using row number and column (name or number)

In [31]:
# selecting a single column
df['Year']

0       2010
1       2015
2       2011
3       2012
4       2013
        ...
7248    2011
7249    2015
7250    2012
7251    2013
7252    2014
Name: Year, Length: 7253, dtype: int64

In [32]:
# selecting multiple column
df[['Name','Year']]

                                                   Name  Year
0                                Maruti Wagon R LXI CNG  2010
1                      Hyundai Creta 1.6 CRDi SX Option  2015
2                                          Honda Jazz V  2011
3                                     Maruti Ertiga VDI  2012
4                       Audi A4 New 2.0 TDI Multitronic  2013
...                                                 ...   ...
7248                  Volkswagen Vento Diesel Trendline  2011
7249                             Volkswagen Polo GT TSI  2015
7250                             Nissan Micra Diesel XV  2012
7251                             Volkswagen Polo GT TSI  2013
7252  Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...  2014

[7253 rows x 2 columns]

In [39]:
# loc()
df.loc[:,'Name']

0                                  Maruti Wagon R LXI CNG
1                        Hyundai Creta 1.6 CRDi SX Option
2                                            Honda Jazz V
3                                       Maruti Ertiga VDI
4                         Audi A4 New 2.0 TDI Multitronic
                              ...
7248                    Volkswagen Vento Diesel Trendline
7249                               Volkswagen Polo GT TSI
7250                               Nissan Micra Diesel XV
7251                               Volkswagen Polo GT TSI
7252    Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...
Name: Name, Length: 7253, dtype: str

In [40]:
df.loc[:,['Name','Year']]

                                                   Name  Year
0                                Maruti Wagon R LXI CNG  2010
1                      Hyundai Creta 1.6 CRDi SX Option  2015
2                                          Honda Jazz V  2011
3                                     Maruti Ertiga VDI  2012
4                       Audi A4 New 2.0 TDI Multitronic  2013
...                                                 ...   ...
7248                  Volkswagen Vento Diesel Trendline  2011
7249                             Volkswagen Polo GT TSI  2015
7250                             Nissan Micra Diesel XV  2012
7251                             Volkswagen Polo GT TSI  2013
7252  Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...  2014

[7253 rows x 2 columns]

In [41]:
df.loc[10:15,['Name','Year']]

                                Name  Year
10                  Maruti Ciaz Zeta  2018
11       Honda City 1.5 V AT Sunroof  2012
12             Maruti Swift VDI BSIV  2015
13  Land Rover Range Rover 2.2L Pure  2014
14    Land Rover Freelander 2 TD4 SE  2012
15       Mitsubishi Pajero Sport 4X4  2014

In [43]:
# select column 'Year' and 'Tranmission' using loc
df.loc[:,['Year','Transmission']]

      Year Transmission
0     2010       Manual
1     2015       Manual
2     2011       Manual
3     2012       Manual
4     2013    Automatic
...    ...          ...
7248  2011       Manual
7249  2015    Automatic
7250  2012       Manual
7251  2013    Automatic
7252  2014    Automatic

[7253 rows x 2 columns]

In [44]:
# selecting rows
# sample() -- select rows ramdomly
df.sample(n=20) # select 20 rows randomly

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
4132,4132,Maruti Swift Dzire ZXI,Chennai,2017,28000,Petrol,Manual,First,20.85,1197.0,83.14 bhp,5.0,NaN,6.25
3066,3066,Audi A6 2011-2015 3.0 TDI Quattro Premium Plus,Pune,2012,50001,Diesel,Automatic,First,14.57,2967.0,241.38 bhp,5.0,NaN,29.00
2247,2247,Maruti Swift Dzire VXI,Kolkata,2014,33485,Petrol,Manual,First,19.10,1197.0,85.8 bhp,5.0,NaN,3.59
725,725,Skoda Yeti Elegance 4X2,Jaipur,2016,84000,Diesel,Manual,First,17.72,1968.0,108.5 bhp,5.0,NaN,11.00
4092,4092,Ford Classic 1.4 Duratorq Titanium,Chennai,2014,83500,Diesel,Manual,Second,19.68,1399.0,67 bhp,5.0,NaN,3.00
4236,4236,Audi A4 35 TDI Premium Plus,Kochi,2015,13506,Diesel,Automatic,First,18.25,1968.0,187.74 bhp,5.0,50.4 Lakh,21.66
833,833,Hyundai i20 1.4 Asta Option,Bangalore,2017,43000,Diesel,Manual,Second,22.54,1396.0,88.73 bhp,5.0,NaN,8.20
7200,7200,Maruti Ritz LDi,Pune,2015,190000,Diesel,Manual,First,23.20,1248.0,73.94 bhp,5.0,NaN,NaN
1176,1176,Fiat Linea Emotion Pack (Diesel),Pune,2010,172050,Diesel,Manual,Second,19.00,1248.0,93 bhp,5.0,NaN,2.25
4258,4258,Hyundai i10 Magna 1.2,Kolkata,2011,38002,Petrol,Manual,First,20.36,1197.0,78.9 bhp,5.0,NaN,2.15
2616,2616,Chevrolet Cruze LTZ AT,Mumbai,2013,59302,Diesel,Automatic,First,14.39,1998.0,163.7 bhp,5.0,NaN,5.25
4197,4197,Chevrolet Beat LT,Coimbatore,2012,24735,Petrol,Manual,Second,18.60,1199.0,79.4 bhp,5.0,NaN,2.87
1985,1985,BMW 3 Series 320d Sport,Chennai,2014,48000,Diesel,Automatic,First,22.69,1995.0,190 bhp,5.0,NaN,21.60
6493,6493,Skoda Laura Ambiente 2.0 TDI CR AT,Pune,2012,75000,Diesel,Automatic,First,20.00,1968.0,138.1 bhp,5.0,NaN,NaN
5318,5318,Mahindra Scorpio S8 8 Seater,Kochi,2016,72118,Diesel,Manual,First,15.40,2179.0,120 bhp,8.0,NaN,10.23
5206,5206,Force One LX 4x4,Kolkata,2014,41000,Diesel,Manual,First,17.00,2200.0,139.01 bhp,7.0,NaN,8.00
6332,6332,Toyota Innova Crysta 2.4 ZX MT,Hyderabad,2017,65896,Diesel,Manual,First,13.68,2393.0,147.8 bhp,7.0,25.04 Lakh,NaN
632,632,Mini Cooper 5 DOOR D,Mumbai,2016,11000,Diesel,Automatic,First,20.70,1496.0,113.98 bhp,5.0,42.12 Lakh,29.50
1025,1025,Chevrolet Beat Diesel,Kochi,2014,52398,Diesel,Manual,First,25.44,936.0,57.6 bhp,5.0,NaN,2.47
1089,1089,Nissan Terrano XL,Mumbai,2014,40000,Petrol,Manual,First,13.24,1598.0,102.5 bhp,5.0,NaN,5.25

In [45]:
df.sample(n=3)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
4894,4894,Maruti Baleno Alpha Diesel,Hyderabad,2017,24000,Diesel,Manual,First,27.39,1248.0,74 bhp,5.0,10.63 Lakh,8.4
6907,6907,Ford Ecosport 1.0 Ecoboost Platinum Edition,Mumbai,2017,15000,Petrol,Manual,First,18.88,999.0,123.24 bhp,5.0,NaN,NaN
6422,6422,Nissan Terrano XV D Pre,Pune,2014,75000,Diesel,Manual,First,19.64,1461.0,108.5 bhp,5.0,16.82 Lakh,NaN

In [47]:
# selet 1% of data from the dataset
df.sample(frac=0.01)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
710,710,Renault Duster 85PS Diesel RxL Optional,Jaipur,2014,75000,Diesel,Manual,First,20.46,1461.0,83.8 bhp,5.0,NaN,7.50
1069,1069,Maruti Swift Dzire VDI,Kolkata,2014,45000,Diesel,Manual,First,23.40,1248.0,74 bhp,5.0,NaN,3.85
1358,1358,Maruti Alto LXi,Coimbatore,2012,49008,Petrol,Manual,First,19.70,796.0,46.3 bhp,5.0,NaN,2.88
4772,4772,Maruti Swift VDI,Kolkata,2014,47000,Diesel,Manual,First,22.90,1248.0,74 bhp,5.0,NaN,3.90
6942,6942,Mercedes-Benz New C-Class C 250 CDI Elegance,Pune,2010,65505,Diesel,Automatic,First,14.94,2143.0,204 bhp,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4515,4515,Toyota Innova 2.5 G (Diesel) 7 Seater BS IV,Pune,2009,118000,Diesel,Manual,First,12.80,2494.0,102 bhp,8.0,NaN,4.50
547,547,BMW 5 Series 2003-2012 520d,Ahmedabad,2012,59900,Diesel,Automatic,Second,18.48,1995.0,177 bhp,5.0,NaN,18.50
2690,2690,Audi A8 L 3.0 TDI quattro,Bangalore,2009,55000,Diesel,Automatic,First,11.80,2967.0,246.7 bhp,5.0,NaN,13.50
4077,4077,Maruti Baleno LXI - BSIII,Kochi,2006,70362,Petrol,Manual,Second,15.40,1590.0,null bhp,5.0,NaN,1.81
4019,4019,Hyundai i20 Sportz 1.4 CRDi,Jaipur,2013,70933,Diesel,Manual,Second,21.90,1396.0,88.76 bhp,5.0,NaN,3.90

In [48]:
df.sample(frac=0.001)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
235,235,Toyota Innova Crysta 2.8 GX AT,Kochi,2019,14165,Diesel,Automatic,First,11.36,2755.0,171.5 bhp,7.0,20.74 Lakh,19.64
6445,6445,Maruti Swift VDI BSIV W ABS,Coimbatore,2016,69564,Diesel,Manual,First,17.80,1248.0,null bhp,5.0,NaN,NaN
5440,5440,Honda Jazz 1.2 V CVT i VTEC,Coimbatore,2017,66507,Petrol,Automatic,Second,19.00,1199.0,88.7 bhp,5.0,NaN,5.43
56,56,Renault KWID RXT,Kochi,2017,16542,Petrol,Manual,First,25.17,799.0,53.3 bhp,5.0,NaN,3.30
3244,3244,Jeep Compass 2.0 Limited Option 4X4,Kolkata,2017,15050,Diesel,Manual,First,16.30,1956.0,170 bhp,5.0,23.19 Lakh,17.50
1281,1281,Hyundai Grand i10 CRDi Sportz Celebration Edition,Kochi,2018,35070,Diesel,Manual,First,24.00,1120.0,70 bhp,5.0,NaN,5.99
1606,1606,Honda Amaze VX i-DTEC,Kochi,2015,61691,Diesel,Manual,First,25.80,1498.0,98.6 bhp,5.0,NaN,5.38

In [49]:
# select row index from 41 to 61
df.iloc[41:62, :]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
41,41,Tata Nano LX SE,Kochi,2014,19698,Petrol,Manual,First,25.40,624.0,37.5 bhp,4.0,NaN,1.53
42,42,Mahindra KUV 100 mFALCON D75 K8 Dual Tone,Coimbatore,2017,22033,Diesel,Manual,First,25.32,1198.0,77 bhp,6.0,NaN,5.58
43,43,Hyundai i20 Magna Optional 1.2,Kochi,2014,35487,Petrol,Manual,First,18.50,1197.0,82.9 bhp,5.0,NaN,4.74
44,44,Hyundai Elantra 2.0 SX Option AT,Bangalore,2014,46374,Petrol,Automatic,First,14.62,1999.0,149.92 bhp,5.0,23.64 Lakh,8.85
45,45,Toyota Corolla Altis G AT,Mumbai,2016,52001,Petrol,Automatic,First,14.28,1798.0,138.03 bhp,5.0,NaN,10.11
46,46,Hyundai Elantra CRDi,Ahmedabad,2008,58005,Diesel,Manual,Second,14.90,1991.0,112.2 bhp,5.0,NaN,4.25
47,47,Toyota Innova Crysta 2.7 GX MT,Bangalore,2012,70704,Petrol,Manual,First,11.25,2694.0,163.7 bhp,7.0,18.64 Lakh,10.95
48,48,Hyundai Xcent 1.1 CRDi S,Jaipur,2014,75000,Diesel,Manual,First,24.40,1120.0,71 bhp,5.0,NaN,3.85
49,49,Mahindra Thar CRDe AC,Jaipur,2012,75800,Diesel,Manual,Second,16.55,2498.0,105 bhp,6.0,NaN,5.50
50,50,Audi A4 2.0 TDI 177 Bhp Premium Plus,Kochi,2015,13648,Diesel,Automatic,First,17.11,1968.0,174.33 bhp,5.0,NaN,21.43
51,51,Maruti Swift LDI,Delhi,2014,52000,Diesel,Manual,First,22.90,1248.0,74 bhp,5.0,NaN,4.25
52,52,Maruti Swift Ldi BSIV,Kolkata,2014,53000,Diesel,Manual,First,17.80,1248.0,75 bhp,5.0,NaN,3.30
53,53,Maruti Swift VDI,Delhi,2013,65650,Diesel,Manual,First,28.40,1248.0,74 bhp,5.0,NaN,3.85
54,54,Hyundai Grand i10 Sportz,Chennai,2015,54000,Petrol,Manual,Third,18.90,1197.0,82 bhp,5.0,NaN,3.60
55,55,Volkswagen Vento 2013-2015 1.6 Comfortline,Kolkata,2015,39000,Petrol,Manual,First,15.04,1598.0,103.2 bhp,5.0,NaN,3.99
56,56,Renault KWID RXT,Kochi,2017,16542,Petrol,Manual,First,25.17,799.0,53.3 bhp,5.0,NaN,3.30
57,57,Hyundai i10 Asta,Kolkata,2010,32000,Petrol,Manual,First,20.36,1197.0,78.9 bhp,5.0,NaN,2.07
58,58,Nissan X-Trail SLX AT,Hyderabad,2010,121812,Diesel,Automatic,First,13.29,1995.0,147.6 bhp,5.0,NaN,7.75
59,59,Maruti Zen Estilo VXI BSIII,Hyderabad,2010,39300,Petrol,Manual,First,18.20,998.0,67.1 bhp,5.0,NaN,2.25
60,60,Toyota Innova Crysta 2.4 GX MT 8S,Mumbai,2017,22000,Diesel,Manual,First,13.68,2393.0,147.8 bhp,8.0,19.34 Lakh,16.50
61,61,Ford Figo Diesel Titanium,Bangalore,2010,72000,Diesel,Manual,First,20.00,1399.0,68 bhp,5.0,NaN,2.75

In [50]:
# select all rows in index 10 to 99, in step 3
df.loc[10:100:3,['Year','Transmission']]

     Year Transmission
10   2018       Manual
13   2014    Automatic
16   2016       Manual
19   2014    Automatic
22   2015    Automatic
25   2012       Manual
28   2018       Manual
31   2012       Manual
34   2014       Manual
37   2017       Manual
40   2008       Manual
43   2014       Manual
46   2008       Manual
49   2012       Manual
52   2014       Manual
55   2015       Manual
58   2010    Automatic
61   2010       Manual
64   2016       Manual
67   2019    Automatic
70   2008    Automatic
73   2015       Manual
76   2008       Manual
79   2005       Manual
82   2016       Manual
85   2009       Manual
88   2016       Manual
91   2014       Manual
94   2014       Manual
97   2010       Manual
100  2011       Manual

In [51]:
df.iloc[10:20:3,5:10]

   Fuel_Type Transmission Owner_Type  Mileage  Engine
10    Petrol       Manual      First    21.56  1462.0
13    Diesel    Automatic      First    12.70  2179.0
16    Diesel       Manual      First    25.80  1498.0
19    Diesel    Automatic      First    14.84  2143.0

# Filter

In [52]:
# select data according to the condition
df.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [53]:
# select all the data where 'Mileage' is >=30
con = df['Mileage']>=30
df[con]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
2701,2701,Maruti Celerio CNG VXI MT,Kochi,2016,70536,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,4.58
3119,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,4.00
3129,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.35 Lakh,3.25
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
3869,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.3 bhp,4.0,NaN,2.10
4141,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,2.85
4769,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.70
5178,5178,Maruti Celerio CNG VXI MT,Delhi,2015,64687,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,3.80
5710,5710,Maruti Alto 800 CNG LXI,Mumbai,2013,26200,CNG,Manual,First,30.46,796.0,47.3 bhp,5.0,NaN,2.15
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
6019,6019,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6538,6538,Maruti Alto K10 LXI CNG,Kochi,2015,47490,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6788,6788,Maruti Alto K10 LXI CNG Optional,Delhi,2017,33000,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,NaN
6958,6958,Maruti Alto 800 CNG LXI,Kolkata,2013,14311,CNG,Manual,First,30.46,796.0,47.3 bhp,5.0,NaN,NaN

In [54]:
# filter data with multiple conditions
# select all data mileage >=30 and tranmission ='manual'
con1 = df['Mileage']>=30
con2 = df['Transmission']=='Manual'
df[con1 & con2]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
2701,2701,Maruti Celerio CNG VXI MT,Kochi,2016,70536,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,4.58
3119,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,4.00
3129,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.35 Lakh,3.25
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
3869,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.3 bhp,4.0,NaN,2.10
4141,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,2.85
4769,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.70
5178,5178,Maruti Celerio CNG VXI MT,Delhi,2015,64687,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,3.80
5710,5710,Maruti Alto 800 CNG LXI,Mumbai,2013,26200,CNG,Manual,First,30.46,796.0,47.3 bhp,5.0,NaN,2.15
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
6019,6019,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6538,6538,Maruti Alto K10 LXI CNG,Kochi,2015,47490,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6788,6788,Maruti Alto K10 LXI CNG Optional,Delhi,2017,33000,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,NaN
6958,6958,Maruti Alto 800 CNG LXI,Kolkata,2013,14311,CNG,Manual,First,30.46,796.0,47.3 bhp,5.0,NaN,NaN

In [55]:
df[con1 & con2].head()

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
2701,2701,Maruti Celerio CNG VXI MT,Kochi,2016,70536,CNG,Manual,First,31.79,998.0,58.33 bhp,5.0,5.87 Lakh,4.58

In [60]:
data = df[con1 & con2]
data[['Name','Year']]

                                   Name  Year
1269  Maruti Alto 800 2016-2019 CNG LXI  2018
1332             Maruti Wagon R CNG LXI  2013
2059             Maruti Wagon R CNG LXI  2013
2371             Maruti Wagon R CNG LXI  2014
2701          Maruti Celerio CNG VXI MT  2016
3119   Maruti Alto K10 LXI CNG Optional  2018
3129             Maruti Wagon R CNG LXI  2014
3553  Maruti Alto 800 2016-2019 CNG LXI  2015
3869  Maruti Alto 800 2016-2019 CNG LXI  2012
4141             Maruti Wagon R CNG LXI  2014
4769  Maruti Alto 800 2016-2019 CNG LXI  2017
5178          Maruti Celerio CNG VXI MT  2015
5710            Maruti Alto 800 CNG LXI  2013
5935            Maruti Alto K10 LXI CNG  2015
6019            Maruti Alto K10 LXI CNG  2014
6538            Maruti Alto K10 LXI CNG  2015
6788   Maruti Alto K10 LXI CNG Optional  2017
6958            Maruti Alto 800 CNG LXI  2013

In [62]:
df[con1 & con2][['Name','Year']]

                                   Name  Year
1269  Maruti Alto 800 2016-2019 CNG LXI  2018
1332             Maruti Wagon R CNG LXI  2013
2059             Maruti Wagon R CNG LXI  2013
2371             Maruti Wagon R CNG LXI  2014
2701          Maruti Celerio CNG VXI MT  2016
3119   Maruti Alto K10 LXI CNG Optional  2018
3129             Maruti Wagon R CNG LXI  2014
3553  Maruti Alto 800 2016-2019 CNG LXI  2015
3869  Maruti Alto 800 2016-2019 CNG LXI  2012
4141             Maruti Wagon R CNG LXI  2014
4769  Maruti Alto 800 2016-2019 CNG LXI  2017
5178          Maruti Celerio CNG VXI MT  2015
5710            Maruti Alto 800 CNG LXI  2013
5935            Maruti Alto K10 LXI CNG  2015
6019            Maruti Alto K10 LXI CNG  2014
6538            Maruti Alto K10 LXI CNG  2015
6788   Maruti Alto K10 LXI CNG Optional  2017
6958            Maruti Alto 800 CNG LXI  2013

In [64]:
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [66]:
df['Location'].unique()

<StringArray>
[    'Mumbai',       'Pune',    'Chennai', 'Coimbatore',  'Hyderabad',
     'Jaipur',      'Kochi',    'Kolkata',      'Delhi',  'Bangalore',
  'Ahmedabad']
Length: 11, dtype: str

In [67]:
location = df[df['Location']=='Pune']
location

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.5
8,8,Volkswagen Vento Diesel Comfortline,Pune,2013,64430,Diesel,Manual,First,20.54,1598.0,103.6 bhp,5.0,NaN,5.2
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.00,2179.0,115 bhp,5.0,NaN,17.5
38,38,Mercedes-Benz M-Class ML 350 CDI,Pune,2013,85000,Diesel,Automatic,First,11.74,2987.0,254.8 bhp,5.0,NaN,28.0
63,63,Mercedes-Benz New C-Class 200 CDI Classic,Pune,2011,65000,Diesel,Manual,Second,15.80,2148.0,170 bhp,5.0,NaN,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7200,7200,Maruti Ritz LDi,Pune,2015,190000,Diesel,Manual,First,23.20,1248.0,73.94 bhp,5.0,NaN,NaN
7228,7228,Tata Tiago 1.05 Revotorq XT Option,Pune,2016,41413,Diesel,Manual,First,27.28,1047.0,69 bhp,5.0,7.06 Lakh,NaN
7230,7230,Hyundai i20 1.2 Spotz,Pune,2014,30315,Petrol,Manual,First,18.60,1197.0,81.83 bhp,5.0,NaN,NaN
7244,7244,Chevrolet Aveo 1.4 LS,Pune,2009,45463,Petrol,Manual,First,14.49,1399.0,92.7 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.6 bhp,5.0,NaN,NaN

In [68]:
location = df[df['Location']=='Pune']['Name']
location

1                Hyundai Creta 1.6 CRDi SX Option
8             Volkswagen Vento Diesel Comfortline
14                 Land Rover Freelander 2 TD4 SE
38               Mercedes-Benz M-Class ML 350 CDI
63      Mercedes-Benz New C-Class 200 CDI Classic
                          ...
7200                              Maruti Ritz LDi
7228           Tata Tiago 1.05 Revotorq XT Option
7230                        Hyundai i20 1.2 Spotz
7244                        Chevrolet Aveo 1.4 LS
7251                       Volkswagen Polo GT TSI
Name: Name, Length: 765, dtype: str

# Filter data with multiple condition OR

In [69]:
# select all data where mileage >=32 or 'Fuel_type' is 'LPG'
df.Mileage.max()

np.float64(33.54)

In [70]:
df.Fuel_Type.unique()

<StringArray>
['CNG', 'Diesel', 'Petrol', 'LPG', 'Electric']
Length: 5, dtype: str

In [72]:
con1 = df['Mileage']>=32
con2 = df['Fuel_Type']=='LPG'
df[con1 | con2]

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
5,5,Hyundai EON LPG Era Plus Option,Hyderabad,2012,75000,LPG,Manual,First,21.10,814.0,55.2 bhp,5.0,NaN,2.35
936,936,Maruti Wagon R LXI LPG BSIV,Hyderabad,2012,72000,LPG,Manual,First,26.20,998.0,58.2 bhp,5.0,NaN,2.85
987,987,Maruti Wagon R LXI DUO BSIII,Mumbai,2008,64226,LPG,Manual,First,17.30,1061.0,57.5 bhp,5.0,NaN,1.45
1269,1269,Maruti Alto 800 2016-2019 CNG LXI,Mumbai,2018,10600,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.50
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2278,2278,Hyundai Santro Xing GLS LPG,Pune,2010,55000,LPG,Manual,Second,13.45,1086.0,62.1 bhp,5.0,NaN,1.65
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
2385,2385,Hyundai Santro Xing GLS LPG,Hyderabad,2011,17000,LPG,Manual,First,13.45,1086.0,62.1 bhp,5.0,NaN,3.10
2436,2436,Hyundai i10 Magna LPG,Jaipur,2012,53000,LPG,Manual,Second,19.20,1086.0,68.05 bhp,5.0,NaN,2.85
2941,2941,Hyundai Santro Xing GL Plus LPG,Hyderabad,2014,56000,LPG,Manual,First,13.45,1086.0,62.1 bhp,5.0,NaN,3.20
3119,3119,Maruti Alto K10 LXI CNG Optional,Kochi,2018,44202,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,4.00
3129,3129,Maruti Wagon R CNG LXI,Delhi,2014,74663,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.35 Lakh,3.25
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
3595,3595,Maruti Wagon R LX DUO BSIII,Hyderabad,2007,65047,LPG,Manual,First,17.30,1061.0,57.5 bhp,5.0,NaN,1.95
3869,3869,Maruti Alto 800 2016-2019 CNG LXI,Delhi,2012,65537,CNG,Manual,Second,33.44,796.0,40.3 bhp,4.0,NaN,2.10
4141,4141,Maruti Wagon R CNG LXI,Mumbai,2014,47200,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,2.85
4769,4769,Maruti Alto 800 2016-2019 CNG LXI,Kochi,2017,24310,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.70
5506,5506,Maruti Wagon R Duo LX BSIII,Hyderabad,2012,72389,LPG,Manual,First,26.20,998.0,58.2 bhp,5.0,NaN,3.20
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
5997,5997,Maruti Wagon R Duo Lxi,Jaipur,2010,70000,LPG,Manual,First,26.20,998.0,58.2 bhp,5.0,NaN,2.27
6019,6019,Maruti Alto K10 LXI CNG,Delhi,2014,40929,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6260,6260,Maruti Wagon R LXI DUO BSIII,Jaipur,2009,87829,LPG,Manual,First,17.30,1061.0,57.5 bhp,5.0,NaN,NaN
6538,6538,Maruti Alto K10 LXI CNG,Kochi,2015,47490,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,NaN,NaN
6788,6788,Maruti Alto K10 LXI CNG Optional,Delhi,2017,33000,CNG,Manual,First,32.26,998.0,58.2 bhp,4.0,4.66 Lakh,NaN
6918,6918,Hyundai A ent Executive LPG,Jaipur,2010,40000,LPG,Manual,Second,13.20,1495.0,93.7 bhp,5.0,NaN,NaN

In [73]:
# selec only name, location, year
df[con1 | con2][['Name','Location','Year']].head()

                                   Name   Location  Year
5       Hyundai EON LPG Era Plus Option  Hyderabad  2012
936         Maruti Wagon R LXI LPG BSIV  Hyderabad  2012
987        Maruti Wagon R LXI DUO BSIII     Mumbai  2008
1269  Maruti Alto 800 2016-2019 CNG LXI     Mumbai  2018
1332             Maruti Wagon R CNG LXI       Pune  2013

In [74]:
# using not condition - select all values except transmission is Manual
df[df['Transmission']!='Manual']

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74
7,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,Diesel,Automatic,First,11.36,2755.0,171.5 bhp,8.0,21 Lakh,17.50
11,11,Honda City 1.5 V AT Sunroof,Kolkata,2012,60000,Petrol,Automatic,First,16.80,1497.0,116.3 bhp,5.0,NaN,4.49
13,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,Diesel,Automatic,First,12.70,2179.0,187.7 bhp,5.0,NaN,27.00
14,14,Land Rover Freelander 2 TD4 SE,Pune,2012,85000,Diesel,Automatic,Second,0.00,2179.0,115 bhp,5.0,NaN,17.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7241,7241,BMW 5 Series 525d Sedan,Delhi,2012,80000,Diesel,Automatic,First,16.73,2993.0,218 bhp,5.0,NaN,NaN
7246,7246,Hyundai Grand i10 AT Asta,Coimbatore,2016,18242,Petrol,Automatic,First,18.90,1197.0,82 bhp,5.0,NaN,NaN
7249,7249,Volkswagen Polo GT TSI,Mumbai,2015,59000,Petrol,Automatic,First,17.21,1197.0,103.6 bhp,5.0,NaN,NaN
7251,7251,Volkswagen Polo GT TSI,Pune,2013,52262,Petrol,Automatic,Third,17.20,1197.0,103.6 bhp,5.0,NaN,NaN
7252,7252,Mercedes-Benz E-Class 2009-2013 E 220 CDI Avan...,Kochi,2014,72443,Diesel,Automatic,First,10.00,2148.0,170 bhp,5.0,NaN,NaN

# sorting data

In [75]:
# sort the data on the basis of mileage in asceding order
df.sort_values(by='Mileage')

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
7226,7226,Hyundai Santro Xing GL,Ahmedabad,2014,41000,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN
5647,5647,Toyota Qualis Fleet A3,Mumbai,2001,227000,Diesel,Manual,Fourth & Above,0.00,2446.0,null bhp,8.0,NaN,2.20
707,707,Mercedes-Benz M-Class ML 350 4Matic,Pune,2014,120000,Diesel,Automatic,First,0.00,2987.0,165 bhp,5.0,NaN,30.00
6697,6697,Hyundai Santro Xing XL,Jaipur,2007,85000,Petrol,Manual,Second,0.00,1086.0,null bhp,5.0,NaN,NaN
6093,6093,Hyundai Santro Xing XL,Bangalore,2007,47000,Petrol,Manual,Second,0.00,1086.0,null bhp,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2059,2059,Maruti Wagon R CNG LXI,Mumbai,2013,54000,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.58 Lakh,3.05
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
4446,4446,Mahindra E Verito D4,Chennai,2016,50000,Electric,Automatic,First,NaN,72.0,41 bhp,5.0,13.58 Lakh,13.00
4904,4904,Toyota Prius 2009-2016 Z4,Mumbai,2011,44000,Electric,Automatic,First,NaN,1798.0,73 bhp,5.0,NaN,12.75

In [77]:
# sort values in decending order
df.sort_values(by='Mileage', ascending=False)['Mileage']

2371    33.54
4141    33.54
3129    33.54
1332    33.54
2059    33.54
        ...
5016     0.00
7226     0.00
14       0.00
4446      NaN
4904      NaN
Name: Mileage, Length: 7253, dtype: float64

In [79]:
# multi level sorting
# sort values by location and mileage
df.sort_values(by=['Location','Mileage'])[['Location','Mileage']]

       Location  Mileage
194   Ahmedabad     0.00
3061  Ahmedabad     0.00
5374  Ahmedabad     0.00
5875  Ahmedabad     0.00
6090  Ahmedabad     0.00
...         ...      ...
5940       Pune    28.40
5935       Pune    32.26
3553       Pune    33.44
1332       Pune    33.54
2371       Pune    33.54

[7253 rows x 2 columns]

In [80]:
df.sort_values(by=['Location','Mileage'], ascending=False)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
1332,1332,Maruti Wagon R CNG LXI,Pune,2013,79494,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,2.96
2371,2371,Maruti Wagon R CNG LXI,Pune,2014,29202,CNG,Manual,First,33.54,998.0,67.04 bhp,5.0,5.54 Lakh,3.90
3553,3553,Maruti Alto 800 2016-2019 CNG LXI,Pune,2015,18000,CNG,Manual,First,33.44,796.0,40.3 bhp,4.0,NaN,3.00
5935,5935,Maruti Alto K10 LXI CNG,Pune,2015,59525,CNG,Manual,Second,32.26,998.0,58.2 bhp,4.0,NaN,3.10
1756,1756,Maruti Swift DDiS VDI,Pune,2008,150000,Diesel,Manual,Second,28.40,1248.0,74 bhp,5.0,NaN,2.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5374,5374,Mercedes-Benz M-Class ML 350 4Matic,Ahmedabad,2012,66000,Diesel,Automatic,First,0.00,2987.0,165 bhp,5.0,NaN,23.00
5875,5875,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,2019,4000,Diesel,Automatic,First,0.00,1950.0,194 bhp,5.0,49.14 Lakh,35.00
6090,6090,Hyundai Santro Xing GL,Ahmedabad,2013,63831,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN
6205,6205,Hyundai Santro Xing GL,Ahmedabad,2007,78000,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN
7226,7226,Hyundai Santro Xing GL,Ahmedabad,2014,41000,Petrol,Manual,First,0.00,1086.0,62 bhp,5.0,NaN,NaN

# Must know functions:

In [81]:
# value_counts()
# sum()
# max()
# mean()
# unique()
# std()

In [82]:
# value_counts() ---counts frequeency of value
df.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

In [83]:
df['Location'].value_counts()

Location
Mumbai        949
Hyderabad     876
Coimbatore    772
Kochi         772
Pune          765
Delhi         660
Kolkata       654
Chennai       591
Jaipur        499
Bangalore     440
Ahmedabad     275
Name: count, dtype: int64

In [84]:
# unique()
df['Transmission'].unique()

<StringArray>
['Manual', 'Automatic']
Length: 2, dtype: str

In [85]:
df['Location'].value_counts()

Location
Mumbai        949
Hyderabad     876
Coimbatore    772
Kochi         772
Pune          765
Delhi         660
Kolkata       654
Chennai       591
Jaipur        499
Bangalore     440
Ahmedabad     275
Name: count, dtype: int64

In [86]:
df['Location'].unique()

<StringArray>
[    'Mumbai',       'Pune',    'Chennai', 'Coimbatore',  'Hyderabad',
     'Jaipur',      'Kochi',    'Kolkata',      'Delhi',  'Bangalore',
  'Ahmedabad']
Length: 11, dtype: str

In [87]:
df['Location'].nunique()

11

In [88]:
df['Fuel_Type'].unique()

<StringArray>
['CNG', 'Diesel', 'Petrol', 'LPG', 'Electric']
Length: 5, dtype: str

In [89]:
df['Fuel_Type'].nunique()

5

In [90]:
df['Fuel_Type'].value_counts()

Fuel_Type
Diesel      3852
Petrol      3325
CNG           62
LPG           12
Electric       2
Name: count, dtype: int64

In [100]:
#max()
df.Mileage.max()

np.float64(33.54)

In [101]:
df.Mileage.min()

np.float64(0.0)

In [102]:
df.Mileage.mean()

np.float64(18.141580471659083)

In [103]:
df.Mileage.std()

np.float64(4.562196601725892)

In [104]:
df.Mileage.median()

np.float64(18.16)

In [105]:
df.Mileage.quantile(0.25)

np.float64(15.17)

In [106]:
df.Mileage.quantile(0.50)

np.float64(18.16)

In [107]:
df.Mileage.quantile(0.75)

np.float64(21.1)

In [108]:
df.Mileage.sum()

np.float64(131544.6)

In [109]:
# find the top most selling Trasmission
df['Transmission'].value_counts()

Transmission
Manual       5204
Automatic    2049
Name: count, dtype: int64

In [110]:
# find top most selling car
df.Name.value_counts().head()

Name
Mahindra XUV500 W8 2WD    55
Maruti Swift VDI          49
Maruti Swift Dzire VDI    42
Honda City 1.5 S MT       39
Maruti Swift VDI BSIV     37
Name: count, dtype: int64

In [111]:
df.head(2)

,S.No.,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50

# dropping, Arranging and renaming columns

In [112]:
# delete (drop) column
df.columns

Index(['S.No.', 'Name', 'Location', 'Year', 'Kilometers_Driven', 'Fuel_Type',
       'Transmission', 'Owner_Type', 'Mileage', 'Engine', 'Power', 'Seats',
       'New_Price', 'Price'],
      dtype='str')

In [128]:
df=df.drop('S.No.', axis=1)

In [129]:
df.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [130]:
# drop multiple columns
# drop year, owner_type
df.drop(['Year','Owner_Type'], axis=1, inplace= True)

In [131]:
df.head()

,Name,Location,Kilometers_Driven,Fuel_Type,Transmission,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,72000,CNG,Manual,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,41000,Diesel,Manual,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,46000,Petrol,Manual,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,87000,Diesel,Manual,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,40670,Diesel,Automatic,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [132]:
# REname col
df.columns

Index(['Name', 'Location', 'Kilometers_Driven', 'Fuel_Type', 'Transmission',
       'Mileage', 'Engine', 'Power', 'Seats', 'New_Price', 'Price'],
      dtype='str')

In [133]:
df.rename(columns={'Kilometers_Driven':'run','Fuel_Type':'fule','New_Price':'price'}, inplace=True)

In [134]:
df.head()

,Name,Location,run,fule,Transmission,Mileage,Engine,Power,Seats,price,Price
0,Maruti Wagon R LXI CNG,Mumbai,72000,CNG,Manual,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,41000,Diesel,Manual,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,46000,Petrol,Manual,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,87000,Diesel,Manual,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,40670,Diesel,Automatic,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [135]:
# column arrange
df.columns

Index(['Name', 'Location', 'run', 'fule', 'Transmission', 'Mileage', 'Engine',
       'Power', 'Seats', 'price', 'Price'],
      dtype='str')

In [124]:
cols=['Location','run','Name','fule','Transmission', 'Mileage', 'Engine',
       'Power', 'Seats', 'price', 'Price']

In [138]:
# dataframe 'df' columns are arranged
df = df[cols]

In [139]:
df.head()

,Location,run,Name,fule,Transmission,Mileage,Engine,Power,Seats,price,Price
0,Mumbai,72000,Maruti Wagon R LXI CNG,CNG,Manual,26.60,998.0,58.16 bhp,5.0,NaN,1.75
1,Pune,41000,Hyundai Creta 1.6 CRDi SX Option,Diesel,Manual,19.67,1582.0,126.2 bhp,5.0,NaN,12.50
2,Chennai,46000,Honda Jazz V,Petrol,Manual,18.20,1199.0,88.7 bhp,5.0,8.61 Lakh,4.50
3,Chennai,87000,Maruti Ertiga VDI,Diesel,Manual,20.77,1248.0,88.76 bhp,7.0,NaN,6.00
4,Coimbatore,40670,Audi A4 New 2.0 TDI Multitronic,Diesel,Automatic,15.20,1968.0,140.8 bhp,5.0,NaN,17.74

In [140]:
# save the file
df.to_csv('cardata_saved.csv',index=False)