In [1]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_excel(r"D:\my project\codeit_datascience\course data\Ecommerce Sales Data.xlsx")
data.head()

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2013-152156,2013,2013-09-11 00:00:00,2013-12-11 00:00:00,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2013-138688,2013,6/13/2013,6/17/2013,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2012-108966,2012,2012-11-10 00:00:00,10/18/2012,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   str
 2   Year           9994 non-null   int64
 3   Order Date     9994 non-null   object
 4   Ship Date      9994 non-null   object
 5   Ship Mode      9994 non-null   str
 6   Customer ID    9994 non-null   str
 7   Customer Name  9994 non-null   str
 8   Segment        9994 non-null   str
 9   Country        9994 non-null   str
 10  City           9994 non-null   str
 11  State          9994 non-null   str
 12  Postal Code    9994 non-null   int64
 13  Region         9994 non-null   str
 14  Product ID     9994 non-null   str
 15  Category       9994 non-null   str
 16  Sub-Category   9994 non-null   str
 17  Product Name   9994 non-null   str
 18  Sales          9994 non-null   float64
 19  Quantity       9994 non-null   int64
 20  Discount       9994 non-null   float64
 21  Profit         9994 non-null   float64
dtypes: float64(3), int64(4), object(2), str(13)
memory usage: 1.7+ MB

In [8]:
# set 'oreder date' and 'ship date' to datetime form
data['Order Date']=pd.to_datetime(data['Order Date'])

In [9]:
data['Ship Date'] = pd.to_datetime(data['Ship Date'])

In [10]:
data[['Order Date', 'Ship Date']].info()

<class 'pandas.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order Date  9994 non-null   datetime64[us]
 1   Ship Date   9994 non-null   datetime64[us]
dtypes: datetime64[us](2)
memory usage: 156.3 KB

In [11]:
data.head(2)

,Row ID,Order ID,Year,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2013-152156,2013,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.96,2,0.0,41.9136
1,2,CA-2013-152156,2013,2013-09-11,2013-12-11,Second Class,CG-12520,Claire Gute,Consumer,United States,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.94,3,0.0,219.5820

# components of datetime

In [15]:
# year -- dt.year --- get only year
data['Order Date'].dt.year

0       2013
1       2013
2       2013
3       2012
4       2012
        ...
9989    2011
9990    2014
9991    2014
9992    2014
9993    2014
Name: Order Date, Length: 9994, dtype: int32

In [16]:
data['Order Date'].dt.month

0        9
1        9
2        6
3       11
4       11
        ..
9989     1
9990     2
9991     2
9992     2
9993     5
Name: Order Date, Length: 9994, dtype: int32

In [17]:
data['Order Date'].dt.day

0       11
1       11
2       13
3       10
4       10
        ..
9989    22
9990    27
9991    27
9992    27
9993     5
Name: Order Date, Length: 9994, dtype: int32

In [19]:
# Get month name
data['Order Date'].dt.month_name()

0       September
1       September
2            June
3        November
4        November
          ...
9989      January
9990     February
9991     February
9992     February
9993          May
Name: Order Date, Length: 9994, dtype: str

In [20]:
# get Day name
data['Order Date'].dt.day_name()

0       Wednesday
1       Wednesday
2        Thursday
3        Saturday
4        Saturday
          ...
9989     Saturday
9990     Thursday
9991     Thursday
9992     Thursday
9993       Monday
Name: Order Date, Length: 9994, dtype: str

# Mathmatcial Operations on Date

In [21]:
data[['Order Date','Ship Date']]

     Order Date  Ship Date
0    2013-09-11 2013-12-11
1    2013-09-11 2013-12-11
2    2013-06-13 2013-06-17
3    2012-11-10 2012-10-18
4    2012-11-10 2012-10-18
...         ...        ...
9989 2011-01-22 2011-01-24
9990 2014-02-27 2014-04-03
9991 2014-02-27 2014-04-03
9992 2014-02-27 2014-04-03
9993 2014-05-05 2014-10-05

[9994 rows x 2 columns]

In [22]:
# find delay date between 'order date' and 'ship date'
data['Ship Date'] - data['Order Date']

0       91 days
1       91 days
2        4 days
3      -23 days
4      -23 days
         ...
9989     2 days
9990    35 days
9991    35 days
9992    35 days
9993   153 days
Length: 9994, dtype: timedelta64[us]

In [29]:
# Add Days
# add 5 days in column 'Order date'
data['Order Date'] + pd.Timedelta(days=5)

0      2013-09-16
1      2013-09-16
2      2013-06-18
3      2012-11-15
4      2012-11-15
          ...
9989   2011-01-27
9990   2014-03-04
9991   2014-03-04
9992   2014-03-04
9993   2014-05-10
Name: Order Date, Length: 9994, dtype: datetime64[us]

In [30]:
# add month -- pd.DateOffset(months=...)
data['Order Date'] + pd.DateOffset(months=4)

0      2014-01-11
1      2014-01-11
2      2013-10-13
3      2013-03-10
4      2013-03-10
          ...
9989   2011-05-22
9990   2014-06-27
9991   2014-06-27
9992   2014-06-27
9993   2014-09-05
Name: Order Date, Length: 9994, dtype: datetime64[us]

In [32]:
# add years
data['Order Date'] + pd.DateOffset(years=2)

0      2015-09-11
1      2015-09-11
2      2015-06-13
3      2014-11-10
4      2014-11-10
          ...
9989   2013-01-22
9990   2016-02-27
9991   2016-02-27
9992   2016-02-27
9993   2016-05-05
Name: Order Date, Length: 9994, dtype: datetime64[us]

In [33]:
data['Ship Date'].dt.year

0       2013
1       2013
2       2013
3       2012
4       2012
        ...
9989    2011
9990    2014
9991    2014
9992    2014
9993    2014
Name: Ship Date, Length: 9994, dtype: int32

In [34]:
data['Ship Date'].dt.month

0       12
1       12
2        6
3       10
4       10
        ..
9989     1
9990     4
9991     4
9992     4
9993    10
Name: Ship Date, Length: 9994, dtype: int32

In [35]:
data['Ship Date'].dt.day

0       11
1       11
2       17
3       18
4       18
        ..
9989    24
9990     3
9991     3
9992     3
9993     5
Name: Ship Date, Length: 9994, dtype: int32

In [36]:
data['Ship Date'].dt.month_name()

0       December
1       December
2           June
3        October
4        October
          ...
9989     January
9990       April
9991       April
9992       April
9993     October
Name: Ship Date, Length: 9994, dtype: str

In [37]:
data['Ship Date'].dt.day_name()

0       Wednesday
1       Wednesday
2          Monday
3        Thursday
4        Thursday
          ...
9989       Monday
9990     Thursday
9991     Thursday
9992     Thursday
9993       Sunday
Name: Ship Date, Length: 9994, dtype: str

In [38]:
data['Ship Date']

0      2013-12-11
1      2013-12-11
2      2013-06-17
3      2012-10-18
4      2012-10-18
          ...
9989   2011-01-24
9990   2014-04-03
9991   2014-04-03
9992   2014-04-03
9993   2014-10-05
Name: Ship Date, Length: 9994, dtype: datetime64[us]

In [ ]:
data['Ship Date'] + pd